### ISSUE TITLE
//protocol-less image URLs

### ISSUE THREAD

**Issue by mull** [cloudinary/cloudinary_gem#102]
Hi folks!

Would it be possible to serve images without a protocol specified? Instead of `http://cdn-5.cloudinary.url` the URL would be `//cdn-5.cloudinary.url` - this way we don't have to force SSL nor do we have to fear images being rejected on HTTPs visitors.

**Comment by edenvicary** [comment]
:+1:

**Comment by edenvicary** [comment]
I've resolved my issue see explination https://github.com/cloudinary/cloudinary_gem/issues/163#issuecomment-118256577

**Comment by taragano** [comment]
Note that the `cl_image_tag` method automatically detects whether the request is over SSL, so for HTTP an `http://...` URL is generated and `https://` for HTTPS.
Please let us know if there's any specific use-case where you'd need a different solution.

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues
