### ISSUE TITLE
Test status badge via Travic CI

### ISSUE THREAD

**Issue by bonsaiben** [cloudinary/cloudinary_gem#104]
It would be nice to see build status badge in the README through Travis CI.

There may be fixes to features that are critical to my application on master, but I need to know the current build status before sourcing to the latest commit.

**Comment by tocker** [comment]
Yes it would be nice - and we are planning to implement it! :smile:

**Comment by d-mendoza** [comment]
We have implemented this feature here (https://github.com/cloudinary/cloudinary_gem#cloudinary).
This ticket will now be closed.
