### ISSUE TITLE
Direct upload + CarrierWave

### ISSUE THREAD

**Issue by philippfrank** [cloudinary/cloudinary_gem#106]
Awesome gem guys, great work. Right now I am trying to figure out how to handle directly uploaded images. I have a working uploader mounted on an ActiveRecord model:

```ruby
image = Image.create
image.file = File.open("my/path.jpg")
image.save!

# image.file_url => "http://res.cloudinary ....
```

When uploading an image directly from the browser, Cloudinary returns:

```ruby
{
  "public_id"=>"opfw720flzvitif30gui", 
  "version"=>"1396726456", 
  "signature"=>"c77782d29ebde75b3a288ecc79d20f039486eadf", 
  "width"=>"600", 
  "height"=>"458", 
  "format"=>"jpg", 
  "resource_type"=>"image", 
  "created_at"=>"2014-04-05T19:34:16Z", 
  "bytes"=>"58428", 
  "type"=>"upload", 
  "etag"=>"90d9dad2d868806f13b01866ae8007fd", 
  "url"=>"http://res.cloudinary.com/wundery/image/upload/v1396726456/opfw720flzvitif30gui.jpg",
  "secure_url"=>"https://res.cloudinary.com/wundery/image/upload/v1396726456/opfw720flzvitif30gui.jpg"
}
````

How can I process this image with my uploader (create the versions) and more important -- update my model.

```ruby
image.file = "v1396726456/opfw720flzvitif30gui.jpg"
image.save!

# image.file_url => nil
```

The following would work but feels kind of hacky and won't solve the version creation:

```ruby
image.raw_write_attribute(:file, "v1396726456/opfw720flzvitif30gui.jpg")
```

The documentation says:

"Note: if you are using direct image uploads from the browser to Cloudinary, a signed identifier is sent to the controller instead of the actual image data. Cloudinary's CarrierWave plugin seamlessly handles direct identifiers, verifies the signature and updates the model with a reference to the uploaded image."
Source: http://cloudinary.com/documentation/rails_carrierwave

I cannot figure out what that means. Cloudinary returns the data I pasted in above.

Thanks in advance!

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
