### ISSUE TITLE
Carrierwave/process: NoMethodError: undefined method `each' for nil:NilClass 

### ISSUE THREAD

**Issue by kipcole9** [cloudinary/cloudinary_gem#110]
Exception produced when process-ing non-standard actions. For example

    process exif

which generates the exception at line 99 in process.rb

         if args.blank?
          send(name).each do
            |attr, value|        
            set_or_yell(@transformation, attr, value)
          end
        end

Issue can be fixed by guarding the send(name):

        if args.blank?
          Array(send(name)).each do
            |attr, value|        
            set_or_yell(@transformation, attr, value)
          end
        end

**Comment by taragano** [comment]
Hi @kipcole9,

I see your last response from quite a time ago. I just wanted to check whether you still experience the same (or any other) issue?

**Comment by taragano** [comment]
@kipcole9 - Do you still experience this issue?
As it's been a while since the last response, I'll close this issue now, but please feel free to re-open it if you need any further assistance.

Thanks
