### ISSUE TITLE
CarrierWave integration via ActiveModel

### ISSUE THREAD

**Issue by kris** [cloudinary/cloudinary_gem#112]
Hi,

I built a project that utilized CarrierWave and ActiveModel w/ Serializable fields for storing the data. This worked great until I started migrating to Cloudinary, and now I get:

    Only ActiveRecord, Mongoid and Sequel are supported at the moment!

I know I could fork this and add an additional condition to check if it matches my system, but was wondering if you have input on using this gem with ActiveModel specifically?

Thanks!

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
