### ISSUE TITLE
Testing with Cloudinary::CarrierWave

### ISSUE THREAD

**Issue by morganick** [cloudinary/cloudinary_gem#113]
Typically when running tests with CarrierWave, you configure CarrierWave to store the files locally giving you local url/access to those files. You also turn off processing for things like images as well. This makes you tests faster and doesn't necessitate having internet access to store/access them.

The problem that we are running into is that when `Cloudinary::CarrierWave` is included into your uploader it changes the configuration at the uploader to use Cloudinary for storage. The CarrierWave test configuration has no effect.

We use VCR to replay external requests that we make. This works great for most request but with Cloudinary the POST data & GET URL are going be unique. Which means I now have tons of cassettes for uploading the same image.

Since I am using `cloudinary_transformation` in my uploader, I cannot make the include of `Cloudinary::CarrierWave` conditional on the environment that I'm in. (e.g. test)

We even toyed with the idea of writing a fake for Cloudinary::CarrierWave that would mimic the API but give us local storage; but we decided against because it's another API to keep in sync & maintain.

The only thing I can think of doing is using `stub_request` matching the URI schema and returning the same body back. This solution will work but is tedious and requires us to keep up with all the file types we test with.

All I really want is to not use Cloudinary in my test env.

Any suggestions? Have I missed something?

**Comment by taragano** [comment]
Hi @morganick, @karlentwistle,

I see your last responses from quite a time ago. I just wanted to check whether you still experience the same (or any other) issue?

**Comment by karlentwistle** [comment]
Still experiencing this issue

**Comment by ka8725** [comment]
Btw, how how to use `cl_image_tag` in tests? Currently it's failing with:

```
Must supply cloud_name in tag or in configuration (ActionView::Template::Error)
```

It seems that with current DSL is not possible to configure application to run in tests.

**Comment by tocker** [comment]
In case this is still an issue: you should include the cloudinary configuration in your test configuration. Either create `cloudinary.yml` in the config directory (make sure to include `test:` configuration) or set the CLOUDINARY_URL environment variable.
