### ISSUE TITLE
Fetching resources by multiple tags

### ISSUE THREAD

**Issue by gingermusketeer** [cloudinary/cloudinary_gem#123]
It would be awesome if this gem allowed fetching resources by multiple tags like `resources_by_tag` but taking a list of tags with an operator `:and/:or`. Is there any way to achieve this with the current api?

**Comment by taragano** [comment]
You can now use the Admin API to list all resources sharing multiple tags. At the moment the resources sharing **all** the tags will be returned (not any). For example:

    Cloudinary::Api.resources_by_tag "tag1,tag2"

**Comment by taragano** [comment]
@gingermusketeer - Did the offer in my last response work for you?
As it's been a while since the last response, I'll close this issue now, but please feel free to re-open it if you need any further assistance.

Thanks

**Comment by gingermusketeer** [comment]
@taragano Sorry for the slow response. I have not tested this as I am not working on a project that needs this feature at the moment. Looks like it covers my use case. Many thanks.
