### ISSUE TITLE
upload_large api does not support tagging the uploaded resource

### ISSUE THREAD

**Issue by gingermusketeer** [cloudinary/cloudinary_gem#130]
Recently we switched from the upload api to the upload_large api. I have just discovered that the upload_large api does not support tagging of the resource. Is there a technical reason for this or has it just not been implemented?

**Comment by tocker** [comment]
Hi @gingermusketeer,

This issue has been fixed. Please Update your cloudinary gem.

**Comment by gingermusketeer** [comment]
@tocker Awesome thanks
