### ISSUE TITLE
CarrierWave upload vs Normal upload - urls

### ISSUE THREAD

**Issue by tdegrunt** [cloudinary/cloudinary_gem#134]
When I'm using the regular Cloudinary::Uploader:
```ruby
results = Cloudinary::Uploader.upload(params[:file])
user.profile_image_url = results['secure_url']
```

I'm getting this url (via secret_url):
https://res.cloudinary.com/cloudname/image/upload/v1420131106/gc5w7yc1jyrzjrgiyr1m.jpg

How can I obtain the same url using the carrier wave integration?

All I can find is (u is a user object):
```ruby
u.avatar_url
```

This gives me:
https://res.cloudinary.com/cloudname/image/upload/gc5w7yc1jyrzjrgiyr1m.jpg

**Comment by taragano** [comment]
Can you please share the installed Cloudinary GEM version and the ORM type?
Also, can you please share a sample code so we'll be able to have a deeper look at this?

**Comment by tdegrunt** [comment]
Sure! I'm using Mongoid:

* mongoid (4.0.0)
* mongoid-grid_fs (2.1.0)
* carrierwave (0.10.0)
* cloudinary (1.0.80)

**Comment by taragano** [comment]
Thank you for sharing the details. We're looking deeper into this and we'll update soon.

**Comment by TalLevAmi** [comment]
solved by 33259599bbeecb845c3c3a08743581fd63ef1c64

**Comment by tocker** [comment]
Hi @tdegrunt, has this issue resolution worked for you?

**Comment by tdegrunt** [comment]
Hi, how can I test this? Any changes to the above code?

**Comment by tocker** [comment]
We have updated the Cloudinary gem to version [1.0.82](https://rubygems.org/gems/cloudinary/versions/1.0.82) including a [fix](https://github.com/cloudinary/cloudinary_gem/commit/33259599bbeecb845c3c3a08743581fd63ef1c64) to the issue you experienced.
Please upgrade to 1.0.82 and test again.

I'd be happy to hear if this indeed solves your issue!

**Comment by tdegrunt** [comment]
We just tested this, this fix solves my issue, thanks!
