### ISSUE TITLE
Supported Language/Framework Versions Inquiry

### ISSUE THREAD

**Issue by Smolations** [cloudinary/cloudinary_gem#141]
I wasn't sure where else to ask this, so this is where it's going for now.  :smile: 

According to the Rails integration guide, the gem has only been tested on Ruby versions up to 1.9.3 and Rails versions up to 4.0.x. Is support for Ruby 2.x (or at least 2.0.x) and Rails 4.1.x in the works? If so, are the estimated completion dates? Will there be alpha and/or beta versions for this support?

Thanks!

**Comment by tocker** [comment]
Hi @Smolations,

We support both Ruby 2.x and Rails 4.1.x.
Thanks for the heads-up! We will amend the documentation.
