### ISSUE TITLE
Make timeout configurable

### ISSUE THREAD

**Issue by jredburn** [cloudinary/cloudinary_gem#143]
Currently, the API call timeout is hard-coded to 60 seconds. For large files hosted on slow connections, we're running into this timeout. Does the Cloudinary service itself enforce a timeout or is this only for the gem?

**Comment by tocker** [comment]
A `:timeout` parameter has been added to the configuration.
See [uploader_spec.rb](https://github.com/cloudinary/cloudinary_gem/blob/master/spec/uploader_spec.rb#L173-185) for an example of use.
