### ISSUE TITLE
Cloudinary::CarrierWave::UploadError: Invalid value aspx for parameter video_file_type

### ISSUE THREAD

**Issue by manuelmeurer** [cloudinary/cloudinary_gem#147]
I have this image:
http://m.exactag.com/ai.aspx?tc=7ff7663f80e740d595b18160db2b7287&url=http://soliver.scene7.com/is/image/soliver/29.502.51.2946.8030_front?
Note that the URL forwards to the final URL: http://soliver.scene7.com/is/image/soliver/29.502.51.2946.8030_front?

Question 1: is it okay to try to upload URLs that forward to the final image? I'm getting these from an external source and it would be nice to use them as-is without doing any manual URL resolution.

Question 2: I get this error when trying to upload the image:
`Cloudinary::CarrierWave::UploadError: Invalid value aspx for parameter video_file_type`
Can I configure Cloudinary/Carrierwave somehow to not look at the file extension but the content type header?

Backtrace:
```
myapp/vendor/bundle/ruby/2.2.0/gems/cloudinary-1.0.82/lib/cloudinary/carrier_wave/storage.rb:40:in `store!'
myapp/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/store.rb:59:in `block in store!'
myapp/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/callbacks.rb:17:in `with_callbacks'
myapp/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/uploader/store.rb:58:in `store!'
myapp/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:375:in `store!'
myapp/vendor/bundle/ruby/2.2.0/gems/carrierwave-0.10.0/lib/carrierwave/mount.rb:207:in `store_file!'
```

This is my configuration:

```ruby
class ImageUploader < CarrierWave::Uploader::Base
  include Cloudinary::CarrierWave
end

class Image < ActiveRecord::Base
  mount_uploader :file, ImageUploader
end
```

I'm using Cloudinary 1.0.82 and CarrierWave 0.10.0

**Comment by tocker** [comment]
Hi @manuelmeurer,

This issue has been fixed.
Can you please retest your code?

**Comment by manuelmeurer** [comment]
Great, thanks! I have no way of testing this right now, since the data comes from an external source, but I'll reopen this issue if it ever happens again. :smile_cat:
