### ISSUE TITLE
Overlay within a folder 

### ISSUE THREAD

**Issue by fiestacasey** [cloudinary/cloudinary_gem#150]
According to support@cloudinary.com:

> For cases where the overlay is inside a folder, you should use the syntax of``` l_<type>:<folder>:<image>```

but this is not the way it is being generated.  Example:

```ruby 
cloudinary_url("production/yc9xzs6fgdbqgx707d1s", transformation=> [{:width=>100, :height=>100, :crop=>:fill}, {:overlay=>"production/opcwlkhskbtmyrbvnrpu", :width=>100, :height=>100, :x=>100, :y=>0, :crop=>:fill}],format: 'jpg')
```

gives http://cl.wantable.com/image/upload/c_fill,h_100,w_100/c_fill,h_100,l_production/opcwlkhskbtmyrbvnrpu,w_100,x_100,y_0/v1/production/yc9xzs6fgdbqgx707d1s.jpg

when it should be 

http://cl.wantable.com/image/upload/c_fill,h_100,w_100/c_fill,h_100,l_upload:production:opcwlkhskbtmyrbvnrpu,w_100,x_100,y_0/v1/production/yc9xzs6fgdbqgx707d1s.jpg

**Comment by taragano** [comment]
Please try to use the following instead:

    cloudinary_url("production/yc9xzs6fgdbqgx707d1s", transformation=> [{:width=>100, :height=>100, :crop=>:fill}, {:overlay=>"upload:production:opcwlkhskbtmyrbvnrpu", :width=>100, :height=>100, :x=>100, :y=>0, :crop=>:fill}],format: 'jpg')

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
