### ISSUE TITLE
Transformation url

### ISSUE THREAD

**Issue by ombr** [cloudinary/cloudinary_gem#151]
Is there any way to do something like this :

```
  Cloudinary::Utils.cloudinary_url(
      cloudinary.file.public_id,
      transformation: { tranformation_string: 'c_fill,h_150,w_100' }
    )
```
I tried : 

```
  Cloudinary::Utils.cloudinary_url(
      cloudinary.file.public_id,
      transformation: { 'c_fill,h_150,w_100' }
    )
```

But it will consider my transformation as a named transformation and append a t_ I would like to be able to just give the transformation string.

Any way to do this easily ?

Thank you.

**Comment by TalLevAmi** [comment]
Yes - 

    Cloudinary::Utils.cloudinary_url(
      cloudinary.file.public_id,
      raw_transformation: 'c_fill,h_150,w_100'
    )

**Comment by ombr** [comment]
Thanks, it works !
