### ISSUE TITLE
How to work with rack using ruby for storing image on cloudinary with gem carrierwave

### ISSUE THREAD

**Issue by ashish19902002** [cloudinary/cloudinary_gem#154]
I am using rack framework with active record and there is no rails , so when i upload image to cloudinary using carrierwave gem i am getting following error 

Unexpected error while processing request: uninitialized constant Cloudinary::CarrierWave::Storage::Rails
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/cloudinary-1.1.0/lib/cloudinary/carrier_wave/storage.rb:71:in `store_cloudinary_identifier'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/cloudinary-1.1.0/lib/cloudinary/carrier_wave/storage.rb:45:in `store!'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/bundler/gems/carrierwave-36dd774ae94c/lib/carrierwave/uploader/store.rb:59:in `block in store!'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/bundler/gems/carrierwave-36dd774ae94c/lib/carrierwave/uploader/callbacks.rb:17:in `with_callbacks'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/bundler/gems/carrierwave-36dd774ae94c/lib/carrierwave/uploader/store.rb:58:in `store!'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/bundler/gems/carrierwave-36dd774ae94c/lib/carrierwave/mounter.rb:99:in `each'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/bundler/gems/carrierwave-36dd774ae94c/lib/carrierwave/mounter.rb:99:in `store!'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/bundler/gems/carrierwave-36dd774ae94c/lib/carrierwave/mount.rb:387:in `store_client_sign!'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:424:in `block in make_lambda'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:221:in `call'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:221:in `block in halting_and_conditional'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `call'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `call'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activesupport-4.1.8/lib/active_support/callbacks.rb:86:in `run_callbacks'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activerecord-4.1.8/lib/active_record/callbacks.rb:302:in `create_or_update'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activerecord-4.1.8/lib/active_record/persistence.rb:103:in `save'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activerecord-4.1.8/lib/active_record/validations.rb:51:in `save'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activerecord-4.1.8/lib/active_record/attribute_methods/dirty.rb:21:in `save'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activerecord-4.1.8/lib/active_record/transactions.rb:268:in `block (2 levels) in save'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activerecord-4.1.8/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activerecord-4.1.8/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activerecord-4.1.8/lib/active_record/transactions.rb:268:in `block in save'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activerecord-4.1.8/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activerecord-4.1.8/lib/active_record/transactions.rb:267:in `save'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activerecord-4.1.8/lib/active_record/persistence.rb:232:in `block in update'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activerecord-4.1.8/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activerecord-4.1.8/lib/active_record/transactions.rb:208:in `transaction'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activerecord-4.1.8/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activerecord-4.1.8/lib/active_record/persistence.rb:230:in `update'
	/home/ashish/mittal/projects/Fyzical/fzupdates_ror/app/api/appointments.rb:330:in `block (3 levels) in <class:Appointments>'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/grape-0.9.0/lib/grape/endpoint.rb:45:in `call'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/grape-0.9.0/lib/grape/endpoint.rb:45:in `block in generate_api_method'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/grape-0.9.0/lib/grape/endpoint.rb:220:in `call'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/grape-0.9.0/lib/grape/endpoint.rb:220:in `run'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/grape-0.9.0/lib/grape/endpoint.rb:171:in `block in call!'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/grape-0.9.0/lib/grape/middleware/base.rb:24:in `call'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/grape-0.9.0/lib/grape/middleware/base.rb:24:in `call!'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/grape-0.9.0/lib/grape/middleware/base.rb:18:in `call'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/grape-0.9.0/lib/grape/middleware/base.rb:24:in `call!'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/grape-0.9.0/lib/grape/middleware/base.rb:18:in `call'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/grape-0.9.0/lib/grape/middleware/error.rb:27:in `block in call!'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/grape-0.9.0/lib/grape/middleware/error.rb:26:in `catch'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/grape-0.9.0/lib/grape/middleware/error.rb:26:in `call!'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/grape-0.9.0/lib/grape/middleware/base.rb:18:in `call'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/grape-0.9.0/lib/grape/endpoint.rb:172:in `call!'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/grape-0.9.0/lib/grape/endpoint.rb:160:in `call'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:152:in `block in call'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:96:in `block in recognize'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:68:in `optimized_each'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:95:in `recognize'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:141:in `call'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/grape-0.9.0/lib/grape/api.rb:128:in `call'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/grape-0.9.0/lib/grape/api.rb:43:in `call!'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/grape-0.9.0/lib/grape/api.rb:39:in `call'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/activerecord-4.1.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/thin-1.6.3/lib/thin/connection.rb:53:in `process'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run_machine'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/eventmachine-1.0.3/lib/eventmachine.rb:187:in `run'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/thin-1.6.3/lib/thin/controllers/controller.rb:87:in `start'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/thin-1.6.3/lib/thin/runner.rb:200:in `run_command'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/thin-1.6.3/lib/thin/runner.rb:156:in `run!'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/gems/thin-1.6.3/bin/thin:6:in `<top (required)>'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/bin/thin:23:in `load'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/bin/thin:23:in `<main>'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/bin/ruby_executable_hooks:15:in `eval'
	/home/ashish/.rvm/gems/ruby-1.9.3-p551@fyzical/bin/ruby_executable_hooks:15:in `<main>'

**Comment by tocker** [comment]
This bug is the result of the way we check the rails version (specifically, [here](https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/carrier_wave/storage.rb#L71)).
Will be fixed shortly.
