### ISSUE TITLE
EXIF data not kept when using Upload Widget

### ISSUE THREAD

**Issue by johnnymitrevski** [cloudinary/cloudinary_gem#155]
Hi,

I am using the Upload Widget to perform direct uploads from the browse,r however when I use a camera the orientation is always in landscape. I believe that the EXIF data is being lost on the upload as I can't see it in the meta data. 

I know this is possible by using :image_metatdata => 'true' or :exif_'true' for direct upload but is there an option that I can set that will keep this data when using the Upload Widget?

Johnny

**Comment by taragano** [comment]
You can indeed set the image_metatdata to true when using the upload widget too. This can be set in the upload preset's settings page in your Admin Console.

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
