### ISSUE TITLE
Wrong file extension is used when generating cloudinary_url

### ISSUE THREAD

**Issue by diazruy** [cloudinary/cloudinary_gem#156]
I am using Cloudinary's Carrierwave integration, and I'm running into an issue with the extension in the URL being incorrect. The value in my DB is stored as `some_image.jpeg`, but when I request the `#url` (or even just the `#filename`, it returns it as `some_image.jpg`, which is incorrect. 

These are images that I am getting [Automatically Uploaded (Origin Pulling)](http://cloudinary.com/blog/how_to_automatically_migrate_all_your_images_to_the_cloud) from S3 through a mapping, which is why these have the `jpeg` extension in the first place. I believe the problem might stem from the use of [`self.format`](https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/carrier_wave.rb#L51) when generating the URL, and CarrierWave must be normalizing this to always be `jpg`.

```ruby
development (main):0 > a.image.url
=> "http://res-1.cloudinary.com/my_cloud/image/upload/v1/my-mapping/some_image.jpg"
development (main):0 > a[:image]
=> "my-mapping/some_image.jpeg"
development (main):0 > a.image.full_public_id
=> "my-mapping/some_image"
development (main):0 > a.image.filename
=> "my-mapping/some_image.jpg"
development (main):0 > a.image.format
=> "jpg"
```

Is it possible to get the URL generated with the original extension?

**Comment by tocker** [comment]
Hi @diazruy,

Cloudinary normalizes the image extension from 'jpeg' to 'jpg'. The `jpeg` extension can still be used - the cloudinary server will automatically convert if needed (for example, `png` will work too!).

CarrierWave may be redundant when using automatic upload mapping. Nonetheless, you can solve your particular issue by adding the following method to your *uploader* class:

```ruby
class ImageUpload < CarrierWave::Uploader::Base
    include Cloudinary::CarrierWave  
    include Versions

    # your code here...

    def format
      if self.version_name.present?
        self.requested_format
      else
        self.file.try(:format) || super
      end
    end
end
```

**Comment by diazruy** [comment]
Thanks for the reply, @tocker.

The code you suggested _does_ fix the issue for me. 

I did debate whether CarrierWave was redundant or not, but decided in the end to keep it around as it affords me:
a) not having to update existing code where I reference `image.version[:small]` or whatever
b) It allows me to keep a centralized list of the existing formats and avoid a proliferation of all sorts of random sizes, which if I was to enable strict transforms, would be much simplified.

Cheers!

**Comment by tocker** [comment]
Great to hear that!

We would love to hear about your experience and insight on this use-case.

**Comment by Steven-Chang** [comment]
Hurray! This saved me too as I am also mapping from s3 right now!
