### ISSUE TITLE
undefined method `file' for #<Cloudinary::CarrierWave::CloudinaryFile

### ISSUE THREAD

**Issue by harsh15** [cloudinary/cloudinary_gem#158]
When I am trying to get the dimensions using minimagick.
Its giving following error
undefined method `file' for #<Cloudinary::CarrierWave::CloudinaryFile

```
  process :store_dimensions
  def store_dimensions
    if(file && model)
      img = ::MiniMagick::Image::read(File.binread(@file.file))
      model.width = img[:width]
      model.height = img[:height]
    end
  end

```

**Comment by taragano** [comment]
I'm sorry for my response delay.

In case you still experience the same issue, I hope the following article should be helpful:
http://support.cloudinary.com/hc/en-us/articles/202519822-How-to-retrieve-image-dimensions-when-uploading-to-Cloudinary-using-CarrierWave-

**Comment by taragano** [comment]
@harsh15 - Do you still experience this issue?
As it's been a while since the last response, I'll close this issue now, but please feel free to re-open it if you need any further assistance.

Thanks
