### ISSUE TITLE
Conflicting transformation on gravity

### ISSUE THREAD

**Issue by Pipinha** [cloudinary/cloudinary_gem#161]
I'm trying to process a transformation

```ruby
version :nav 
  resize_to_fill(45, 45)
  cloudinary_transformation :gravity => :faces
end
```

And the returning is "conflicting transformation on gravity faces!=center"

**Comment by taragano** [comment]
Please try the following instead:

```ruby
version :nav 
  resize_to_fill(45, 45, 'faces')
end
```
A third argument can be passed representing the gravity.

**Comment by Pipinha** [comment]
Thanks @taragano!
