### ISSUE TITLE
HTTPS not working in SCSS method `cloudinary_url`

### ISSUE THREAD

**Issue by edenvicary** [cloudinary/cloudinary_gem#163]
When setting `config.secure = true` in cloudinary.rb it brings all of the static assets from `cl_image_tag` but the assets pulled through the `cloudinary_url` method in SCSS are still pulled through https. We need to force SSL on our site and having assets pulled in over https communicates to the user a lack of trustworthiness.

We are using the latest rails on heroku with Cloudinary Gem 1.1.0

Please help?

**Comment by edenvicary** [comment]
I've fixed our issue by adding `$secure: true` to the `cloudinary-url`call in SCSS. This as the solution wasn't very obvious, so I would appreciate if it took the settings from the definitions used by the other methods.

**Comment by taragano** [comment]
Hi,
Note that assets are compiled in a different environment (assets). Please make sure the config.secure line is done in the correct env.
