### ISSUE TITLE
cl_video_tag causes undefined method `sub' for #<VideoUploader...

### ISSUE THREAD

**Issue by bradleygauthier** [cloudinary/cloudinary_gem#166]
I believe this is a bug with the cl_video_tag (https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/video_helper.rb#L23)

We are using the latest releases of the Carrierwave and Cloudinary gems. Also, the other video related tags like cl_video_path and cl_video_thumbnail_tag work.

The trace shows it's an issue with stripping the file format extension:

```
cloudinary (1.1.0) lib/cloudinary/video_helper.rb:96:in `strip_known_ext'
cloudinary (1.1.0) lib/cloudinary/video_helper.rb:24:in `cl_video_tag'
```

Maybe related to this issue: When we direct upload from the browser the asset is saved with /video/upload/ prepended to the version/video_id.ext string. When we upload images, the /image/upload/ is stripped. We cannot find any way to change this behavior.

Thank you for your help!

**Comment by taragano** [comment]
Hi,

As we couldn't reproduce this issue, can you please share some more of your code? It may be easier to continue this via a support ticket (I responded to you there too).

**Comment by bradleygauthier** [comment]
Yes, I believe it is a specific error inside our app that has to do with this Carrierwave update: https://github.com/cloudinary/cloudinary_gem/commit/ebdbfd7142fa0b728196e0012d11e8dafa7f0f05#diff-04c6e90faac2675aa89e2176d2eec7d8R152

**Comment by arpancj** [comment]
I'm seeing this same error in my app. 

@bradleygauthier did you find a fix for this?
