### ISSUE TITLE
field: file is set as "_old_"

### ISSUE THREAD

**Issue by Pipinha** [cloudinary/cloudinary_gem#168]
Hi guys,

When I update my object from the console, the image field is setting with "_old_".

>Photo _id: 556d225e69702d45b0000000, created_at: 2015-07-30 02:20:30 UTC, updated_at: 2015-07-30 02:27:09 UTC, file: "_old_", title: nil, description: nil, position: nil, user_id: nil

**Comment by tocker** [comment]
The "\_old\_" value is a temporary value which is set to force mongoid to persist the field ([source](https://github.com/carrierwaveuploader/carrierwave-mongoid/blob/master/lib/carrierwave/mongoid.rb#L39)). This is done by CarrierWave and not Cloudinary. 
You should persist the model (by calling `save`) and then check the value of  `file`.

Also, please note that the only valid values for the field are either a Cloudinary identifier in the format of `"#{resource_type}/#{type}/v#{version}/#{filename}##{signature}"` or a `File` object.

For example,

```ruby
mymodel.file = File.open(path_to_local_file)
mymodel.save
```

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
