### ISSUE TITLE
Rails 4

### ISSUE THREAD

**Issue by fabdelgado** [cloudinary/cloudinary_gem#170]
How to implement in rails 4 Cloudinary?

No achievement integrate with the examples detailed in the readme.

**Comment by edenvicary** [comment]
"If you use Rails 3.x or higher, edit your..."

**Comment by taragano** [comment]
I'm sorry for my response delay.

Our GEM is supported for Rails 4, the integration is pretty straightforward.
Did you encounter with any specific issue?

**Comment by fabdelgado** [comment]
Yes, at the moment I do not remember.
If you find a mistake, I'll write.
