### ISSUE TITLE
image-url not changed to cloudinary CDN URLs in generated CSS

### ISSUE THREAD

**Issue by MadameSardine** [cloudinary/cloudinary_gem#172]
I''m using the Cloudinary add-on for Heroku for my Rails 4 app.
For all the image_tag in my views, a Cloudinary CDN URL is generated.
However, no Cloudinary CDN URL is generated for the image-url in my sass/css files.
If I take the example in Cloudinary's tutorial, the following Sass code:

`.logo
    background-image: image-url("logo.png")`

should generate this CSS:

`.logo { background-image: url(http://res.cloudinary.com/demo/image/asset/logo-5740ed843b23d0b86e48081f43a45b9c) }`

but I have instead:

`.logo { background-image: url(/assets/logo-5740ed843b23d0b86e48081f43a45b9c.png)}`

Does anyone have the same issue / know a fix?
Thanks!

**Comment by taragano** [comment]
Hi @MadameSardine,

I'm sorry for my response delay here.
I see we've also discussed this over a private support a while ago, so I'll be closing this issue for now. If you have any other issues you need assistance with, please always feel free to contact support@cloudinary.com.

For the other viewers,  please try to use the following instead:

    .logo background-image: cloudinary-url("logo.png")
