### ISSUE TITLE
SSLCertificateNotVerified when trying to upload

### ISSUE THREAD

**Issue by haggen** [cloudinary/cloudinary_gem#173]
I'm using Cloudinary for the first time, in a Rails 4 application, running in a Docker container.

The thing is, I can't upload anything, every time I try I get `SSLCertificateNotVerified` error from RestClient.

Any ideas ?

Thanks.

**Comment by TalLevAmi** [comment]
Looks like your certificate file is not up-to-date. Please make sure to update it according to the base image you are using.

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Comment by haggen** [comment]
Oh I'm sorry, totally forgot to update the issue. 

You were right, I was running it from inside a (Docker) container that hasn't had installed `ssl-certificates`.

After an `apt-get install` it got working just fine! Thanks!
