### ISSUE TITLE
How do you generate a signed authentication request?

### ISSUE THREAD

**Issue by edenvicary** [cloudinary/cloudinary_gem#183]
Ok, so I'm trying to upload images from our mobile client and the docs suggest that we get auth JSON object from the server.

https://github.com/cloudinary/cloudinary_ios#safe-mobile-uploading
>You can use any Cloudinary libraries (Ruby on Rails, PHP, Python & Django, Java, Perl, .Net, etc.) on your server to generating the upload signature. The following JSON in an example of a response of an upload authorization request to your server:
>
```
{
  "signature": "sgjfdoigfjdgfdogidf9g87df98gfdb8f7d6gfdg7gfd8",
  "public_id": "abdbasdasda76asd7sa789",
  "timestamp": 1346925631,
  "api_key": "123456789012345",
}
```

Which method do I call to generate this? I've found it quite hard to find within the docs everywhere references this link http://cloudinary.com/documentation/upload_images#request_authentication but that tag doesn't go anywhere...

**Comment by taragano** [comment]
Our documentation page was recently updated, here's the new link:
http://cloudinary.com/documentation/upload_images#creating_api_authentication_signatures

You can pass the upload options to the `sign_request` method, for example:

    Cloudinary::Utils.sign_request({timestamp: 1455455583, public_id: "my_image"})

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues
