### ISSUE TITLE
Options not accepted in jQuery.fn.cloudinary_fileupload

### ISSUE THREAD

**Issue by udit7590** [cloudinary/cloudinary_gem#184]
There seems to be an issue in jquery.cloudinary.js file. I am trying to pass options as:
$(selector).cloudinary_fileupload({
    dropZone: _this.$fileBlock,
    maxFileSize: _this.options.maxFileSize,
    acceptFileTypes: _this.options.allowedFileTypes,
  })
But when max file validations are not being added. In fact when I tried to debug it, it shows options argument to be undefined.

**Comment by taragano** [comment]
Note that there are additional includes to be made for client-side validation. For more information:
https://github.com/cloudinary/cloudinary_js#client-side-image-resizing-before-upload

If you use the asset pipeline, you can require `cloudinary/processing`. See:
https://github.com/cloudinary/cloudinary_gem/blob/master/samples/photo_album/app/assets/javascripts/application.js#L17

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues
