### ISSUE TITLE
While uploading image to cloudinary getting Invalid extension in transformation

### ISSUE THREAD

**Issue by BeenaShetty** [cloudinary/cloudinary_gem#190]
while uploading image through remote_photo_url
Error message

A Cloudinary::CarrierWave::UploadError occurred in tokens#create:

Invalid extension in transformation: jpgsz280

**Comment by taragano** [comment]
I could reproduce this issue when doing something like the following in the uploader code:

    process :convert => "jpgsz280"
In case this is a typo, please change it to:

    process :convert => "jpg"
Otherwise, can you please share some more of your uploader code?

**Comment by BeenaShetty** [comment]
Thanks
