### ISSUE TITLE
How do I copy image from one model to another?

### ISSUE THREAD

**Issue by toppy42** [cloudinary/cloudinary_gem#191]
We're in the process of migrating some of our data to a different model and I'm trying to copy the image information over, but I can't figure out how to do it properly.

`model2.image = model1.image` does not actually copy the file (of type Cloudinary::Carrierwave::CloudinaryFile), but instead creates a new file (of type Cloudinary::CarrierWave::RemoteFile).  This new file generates a vastly different URL to an image that doesn't exist.

How do I accomplish this?
Thank you!

**Comment by thedrow** [comment]
This is not documented anywhere but I discovered it by browsing through the code.
You need to use `Cloudinary::CarrierWave::StoredFile`.
``ruby
model2.image = Cloudinary::CarrierWave::StoredFile.new(model1.image.identifier)
```
will work.
Maybe we should document this somewhere?

**Comment by toppy42** [comment]
@thedrow Thanks for the response.  That method above gives me the error `ArgumentError: File prod_images/v1401716415/lil6mkrdon4iuajtcj6q.png is illegal`

Any idea?

**Comment by toppy42** [comment]
So after some more digging, I realized that the 'prod_images' prefix is causing the StoredFile instantiation to fail.  We add this prefix because this is on our dev environment, and we have a mapping set up in our cloudinary settings to forward those requests to production.

I can remove the prefix and re-add it later when not in prod, but that's an ugly solution.  Any suggestions for a better method?

**Comment by thedrow** [comment]
No sorry.

**Comment by toppy42** [comment]
No worries, thanks

**Comment by tocker** [comment]
@toppy42 how about the following:

```ruby
class Cloudinary::CarrierWave::StoredFile
  def self.toppy(identifier)
    identifier = /^(?:[^\/]+\/)?(v\d+\/[^#]+)$/.match(identifier)[1] if Rails.env.development?
    new(identifier)
  end
end

# both work
model2.image = Cloudinary::CarrierWave::StoredFile.toppy "prod_images/v1401716415/lil6mkrdon4iuajtcj6q.png"
model2.image = Cloudinary::CarrierWave::StoredFile.toppy "v1401716415/lil6mkrdon4iuajtcj6q.png"

# or 

class Toppy < Cloudinary::CarrierWave::StoredFile
  def initialize(identifier)
    identifier = /^(?:[^\/]+\/)?(v\d+\/[^#]+)$/.match(identifier)[1] if Rails.env.development?
    super(identifier)
  end
end

# both work
model2.image = Toppy.new "prod_images/v1401716415/lil6mkrdon4iuajtcj6q.png"
model2.image = Toppy.new "v1401716415/lil6mkrdon4iuajtcj6q.png"
```

Keep in mind this is a simplified solution 😄 !

**Comment by toppy42** [comment]
Figured out the issue but forgot to post the answer, it was because we were putting "prod_images" in front of the url string, but it needs to be after the version and before the filename
eg. `v1401716415/prod_images/lil6mkrdon4iuajtcj6q.png`

**Comment by vestedpr-dev** [comment]
Hi -- just wanted to comment -- today I was refactoring my Rails code, extracting a bunch of models out, into a separate model ... a part of this is moving the pointer of some Carrierwave Cloudinary images to the new model.  I expected this to take about 5 minutes.

But instead it took me about two hours of spelunking through the code, before I finally ended up here.

This is such a common thing which, anyone who uses this gem is going to experience.  I would suggest documenting this towards the bottom of the main Readme file.

For future reference to other lost souls like myself -- to move the pointer of a Carrierwave Cloudinary attachment from one model to another, get your Uploaders all sorted out, then do something like this:

```
      if original_model.image_cloudinary.present?
        image_cloudinary = Cloudinary::CarrierWave::StoredFile.new(original_model.image_cloudinary.identifier)
      else
        image_cloudinary = nil
      end

      NewModel.create!(
        image_cloudinary: image_cloudinary,
      )
```

**Comment by taragano** [comment]
Thanks so much for this @vestedpr-dev. Very valuable information indeed.
We'll definitely add this info.
