### ISSUE TITLE
Utils::cloudinary_url() builds URLs incorrectly which causes Uploader::exists? to report false negatives

### ISSUE THREAD

**Issue by thedrow** [cloudinary/cloudinary_gem#193]
I'm using the the latest Cloudinary gem with CarrierWave 0.11.
When I upload a photo I expect mymodel.photo.file.exists? to return true (or currently 0 which #192 fixes) however I get false.
When I access the URL provided from mymodel.photo.url I get the following output:
https://res.cloudinary.com/fiverr-dev/image/upload/v1459337125/hc0b2stbr5zfla49klni.jpg
And the server returns the image as expected. HEAD requests respond with 200 OK as expected as well.
However it seems that there is a bug in Cloudinary::Utils.cloudinary_url() that causes it to build URLs incorrectly.
The method returns:
http://res.cloudinary.com/fiverr-dev/image/upload/v1/image/upload/v1459337125/hc0b2stbr5zfla49klni

Which doesn't exist in on the server.
Any idea how to fix this bug?

**Comment by taragano** [comment]
Hi @thedrow,

Regarding the `exists?` method that returns false - I'm passing this to our team to have a look at it.

Regarding the `cloudinary_url` method, can you please share a code example including the given arguments?

Note that you can use CarrierWave's helper method to generate the URL, e.g.

    mymodel.photo.url 
that should return the correct URL.

**Comment by thedrow** [comment]
I'll have to debug the code and print all the arguments. Give me a day and you'll have the info you need.

**Comment by thedrow** [comment]
I'm pretty sure I know what went wrong.
The CarrierWave integration stored the public id as image/upload/v1459863308/oft01mchh5gpe2plzhmo.jpg
which of course results in an incorrect URL.

**Comment by thedrow** [comment]
The issue is that inside CarrierWaveFile you guys are calling exists? with self.identifier instead of self.public_id.
```ruby
# line 173 in lib/cloudinary/carrier_wave
def exists?
  Cloudinary::Uploader.exists?(self.public_id, :type=>self.storage_type, :resource_type=>self.resource_type)
end
```
Works as expected because
```ruby
self.public_id = "uzlhnkcd3jij7s8o1jad"
self.identifier = "image/upload/v1459863978/uzlhnkcd3jij7s8o1jad.jpg"
```
The same is done with CarrierWave::read() btw.
I believe the correct code is in delete():
```
public_id = @resource_type == "raw" ? self.filename : self.public_id
```
But I'm not sure.

**Comment by taragano** [comment]
Thank you @thedrow.
I'm passing this to our team and we'll let you know of any updates.

**Comment by matheussilvasantos** [comment]
I'm using the `cl_image_tag` method and I'm getting the wrong URL too. What is different between one URL with another is that one has `/v1/` and the other is `/v1509894856/`.

**Comment by matheussilvasantos** [comment]
I think the problem is here https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/utils.rb#L394.

Cloudinary is generating a new version each time for the uploaded images. But in the gem it always use v1.

**Comment by thedrow** [comment]
So is this fixed in https://github.com/cloudinary/cloudinary_gem/commit/dd8fd69d9406545defda46598ef511e516766157 ?

**Comment by matheussilvasantos** [comment]
It is not, because the problem is here https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/utils.rb#L394-L395. It get `v1` always.

**Comment by strausr** [comment]
@thedrow This issue is indeed fixed.

@matheussilvasantos Both versions v1 and v1366687335, for example, would render the URL correctly. Versions are required for building URLs of the latest uploaded version of an image in case that multiple images were uploaded sharing the same public ID. That being said, we don't require the version component to be present in URLs.

If you require further assistance in this manner, we'd be happy to take it offline and assist you with a 1-1 ticket. Please open a ticket at support@cloudinary.com

Thanks

**Comment by thedrow** [comment]
Very well, I'm closing this issue :)
