### ISSUE TITLE
Local public ID can differ from Cloudinary asset

### ISSUE THREAD

**Issue by alextaylor000** [cloudinary/cloudinary_gem#196]
This appears to be by design at the moment, but I'm curious why in the CarrierWave integration `public_id` has been [implemented in a way](https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/carrier_wave.rb#L76) that allows it to differ from what gets uploaded to Cloudinary.

Background: I need the `public_id` of an image stored in my database in order to pass it into an overlay for a Cloudinary transformation.

For example, when using the Cloudinary API to upload a file, Cloudinary will generate a public ID:

```ruby
Cloudinary::Uploader.upload(File.open('/path/to/my/file.png'))

# => {"public_id"=>"pq27y6cmp1xkipzr6bxy", "version"=>1460477904, ...
```

If I need to access this resource by its public ID, I can use

```ruby
Cloudinary::Api.resource('pq27y6cmp1xkipzr6bxy')
```

However, when I use the same uploader and attach the file to a record using CarrierWave:

```ruby
class ApplicationUploaderBase < CarrierWave::Uploader::Base
  include Cloudinary::CarrierWave

  # not overriding public_id here; I want Cloudinary to generate one for me
end
```

```ruby
    File.open(my_file) do |f|
      @user.avatar = f
      @user.save!
    end
 ```

A `public_id` is generated, but I cannot access it through the uploader since `public_id` returns nil:

```ruby
  @user.avatar.public_id
  # => nil
```

However, using `my_public_id` works as expected:

```ruby
  @user.avatar.my_public_id
  # => pq27y6cmp1xkipzr6bxy
```

I can use `my_public_id` for my purposes at the moment, but I'm concerned about relying upon this method - is it safe to do so?

Thanks guys!

**Comment by roeeba** [comment]
The `my_public_id` method is indeed a legitimate method for retrieving the public ID of an uploaded image.
The `public_id` method is a setter of the public ID when uploading an image, and is defined at the uploader itself.

Note that the `cl_image_tag` and `cloudinary_url` methods support getting the actual Carrierwave Uploader instance instead, and our GEM will take care of the public ID parsing automatically, e.g.,:

```
cl_image_tag(@user.avatar, format: :jpg)
```

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
