### ISSUE TITLE
Thumb version returns an empty image

### ISSUE THREAD

**Issue by besi** [cloudinary/cloudinary_gem#197]
Hy there, I am using CarrierWave together with Cloudinary.

This is an image I have uploaded:

    http://res.cloudinary.com/mediacloud/image/upload/v1459845058/amzwe7vrjssx4p08dkyr.jpg

Now I somehow the thumb-version does not seem to work and an empty image is returned.

    http://res.cloudinary.com/mediacloud/image/upload/c_fill,h_64,w_64/v1459845058/amzwe7vrjssx4p08dkyr.jpg

I am using these gems:

    gem 'carrierwave', github: 'carrierwaveuploader/carrierwave', branch: 'master'
    gem 'cloudinary'

**Comment by roeeba** [comment]
Hi besi, it seems that there is currently no image with public ID - 'amzwe7vrjssx4p08dkyr' on your account. Can you please share a fresh example that demonstrates the issue? thanks!

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
