### ISSUE TITLE
Cloudinary::CarrierWave::CloudinaryFile#exists? doesn't work

### ISSUE THREAD

**Issue by samphilipd** [cloudinary/cloudinary_gem#205]
It uses the `identifier` and it should be using `public_id`.

**Comment by taragano** [comment]
@samphilipd - Will you be able to please confirm the referenced commit solves the issue you reported?

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
