### ISSUE TITLE
Cloudinary::Migrator is not set up for use.

### ISSUE THREAD

**Issue by Lyonsclay** [cloudinary/cloudinary_gem#206]
Looking at the documentation on the website there is a super helpful way to migrate resources from a model using Cloudinary::Migrator. Unfortunately, the cloudinary.rb module is not set up to autoload the Migrator which is in lib/cloudinary/migrator.rb.  Is there a reason this isn't setup like it has been deprecated or not supported yet?

**Comment by taragano** [comment]
Hi @Lyonsclay,
You actually don't need to access the `Cloudinary::Migrator` class directly.
Please try to go through the steps as explained in the following:
http://cloudinary.com/blog/how_to_deliver_your_static_images_through_a_cdn_in_ruby_on_rails

**Comment by Lyonsclay** [comment]
Thanks @tarango!

**Comment by taragano** [comment]
I'm glad I could of assistance @Lyonsclay :)
