### ISSUE TITLE
Uploading images with a dynamic custom config possible?

### ISSUE THREAD

**Issue by paulgoetze** [cloudinary/cloudinary_gem#207]
I want to use custom Cloudinary clouds and api credentials on a request level. Suppose I have a Rails app with a default initial Cloudinary config defined with

``` ruby
Cloudinary.config do |config|
  config.cloud_name = 'my-cloudname'
  config.api_key    = 'my-apikey'
  config.api_secret = 'my-secret'
end
```

and custom different cloudinary configs per user.
My goal is to use the user’s custom config for uploading and getting images to and from Cloudinary.

To achieve this, I 

**A) overwrote the `transformation` method of my `ImageUploader` class:**

``` ruby
class ImageUploader < CarrierWave::Uploader::Base
  include Cloudinary::CarrierWave

  # Merge transformations with cloudinary API credentials to pass them as
  # options into Cloudinary::Uploader.upload().
  # See https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/carrier_wave/storage.rb#L27
  # and https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/uploader.rb#L277-280
  def transformation
    super.merge(
      cloud_name: 'custom-cloudname',
      api_key:    'custom-apikey',
      api_secret: 'custom-apisecret'
    )
  end

 # ...
end
```

**B) Passed the custom config to the `cl_image_upload_tag` method in my upload form:**

``` ruby
<%=
  cl_image_upload_tag(image.object_name + "[file]",
  {
    folder: user.to_param,
    html: {
      multiple: false,
      accept: "image/*"
    },
    cloud_name: 'custom-cloudname',
    api_key:    'custom-apikey',
    api_secret: 'custom-apisecret'
  }
) %>
```

**C) Passed the custom config to the `image` function in JS where needed:**

``` js
// options is an object holding the `cloud_name` and `api_key` attributes, amongst others
$.cloudinary.image(public_id, options);
```

The credentials in the code examples are of cause always fetched dynamically from a model.

It works so far. Only the final upload fails with an `Invalid signature` error message.
I searched in the code and it looks like the `valid?` method of the `Cloudinary::PreloadedFile` is always using the api secret from `Cloudinary.config.api_secret` and there is no way to overwrite it by using a custom one. 
See https://github.com/cloudinary/cloudinary_gem/blob/972d116879686788c274e2f78d458626400b6551/lib/cloudinary/preloaded_file.rb#L12

Is there/should there be a way to pass custom configs on a request level for uploading/fetching images?

**Comment by taragano** [comment]
Hi @paulgoetze,

My apologies for the long delay in my response.

In case this is still relevant, indeed the `valid` method is based on the global settings of the app. Possible workarounds for that are to either manually override the `valid` method to match the credentials of the corresponding account, or temporarily change the global credentials to fit the new account before the upload, and redefine the default account after the upload.

Regardless, I've passed it on to our dev team to consider supporting such a use-case in one of our future versions.

**Comment by paulgoetze** [comment]
:+1: Thanks, @taragano, for passing it to the dev team.

**Comment by nadavofi** [comment]
Hi @paulgoetze,
Such use-case and functionality should become better supported as part of a more broad solution that is already on our roadmap. Meantime, I'd like to suggest a couple of workarounds that may help to tackle the issue you're facing.

1. Probably the easiest solution would be to override the `valid?` method returning a simple **true** answer to the caller:
2. Alternatively, if you wish to preserve this validation, then you will can try to override the `valid?` method and provide it with the Cloudinary context in which it should run, similar to how it's done on your `ImageUploader`. As the code you've shared above uses literal definitions of the custom configuration, we can't test to see if this will work. Can you give it a try?

Well be happy to look deeper into your implementation If you don't mind sharing access to your code repository.

**Comment by paulgoetze** [comment]
Since the issue was opened I changed jobs. So, unfortunately, I don’t have access to the codebase anymore :(. This said, a solution for this issue is not essential for me anymore right now. I still think it’s a use case that should be covered.

Anyways, thanks @nadavofi for the workaround hints! Might help someone else already until your upcoming changes are out.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
