### ISSUE TITLE
Cloudinary::Utils.download_archive_url generates a url with spaces in it

### ISSUE THREAD

**Issue by designstuhl** [cloudinary/cloudinary_gem#209]
I am using the download_archive_url method to create an archive and send a link to the user via a mailer. Using puts calls I can verify that the url is correct at the worker and mailer level, but when I click on the link in the email it opens with spaces in the url causing an Invalid Signature error message. The longer the generated URL is, the more spaces I see in the URL. 

I was originally using the Cloudinary::Uploader.create_archive method but this doesn't allow me to set an expires_at parameter according to the documentation on the API. 

I have tried this with the download_zip_url as well and got the same result. Any ideas what the problem could be?

**Comment by roeeba** [comment]
Hן @designstuhl , sorry for the late reply. If it's still relevant, can you please share with us the download_archive_url generated URL, which raises the Invalid Signature error, so we can check it further? thanks!

**Comment by roeeba** [comment]
Hi @designstuhl , I see that this enquiry was addressed via a support ticket, therefore I'm closing the ticket now. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
