### ISSUE TITLE
Refile-cloudinary?

### ISSUE THREAD

**Issue by Jamevidi** [cloudinary/cloudinary_gem#214]
I love rails refile and Cloudinary looks super awesome. I currently use refile-s3 gem.
Is there any similar refile-cloudinary gems or plans to make one?

Thanks for any input! :)

**Comment by nadavofi** [comment]
Cloudinary doesn't currently integrate to Refile's gem.
Are you familiar with our Cloudinary-Carrierwave integration? We encourage you to check it out and see if it works.

Also, if you notice any missing functionalities, please don't hesitate to share it here or in a support ticket.

**Comment by Jamevid** [comment]
Thanks for the answer! :)

So until there is a Refile integration...would "Origin pulling - Automatic image uploading " from S3 work?

source:http://cloudinary.com/blog/how_to_automatically_migrate_all_your_images_to_the_cloud

Like this:
1. I upload to S3 with Refile
2. Use "Origin pulling" to Cloudinary from S3 bucket?

If yes, would actually any uploading gem work with Cloudinary as long as files can be pulled from S3?

Thanks !!

**Comment by nadavofi** [comment]
Absolutely. The Upload-Mapping (Auto-Upload) feature is a generic solution which can fit any publicly available images around the web, as well as private S3 buckets which need to be whitelisted in advance - 

Please [contact our support](https://support.cloudinary.com/hc/en-us/requests/new) and we'll be happy to whitelist it for you if required.

**Comment by Jamevid** [comment]
Thats great news! Thanks for quick response! :-)

**Comment by d-mendoza** [comment]
Closing account due to inactivity and solution via auto-upload mapping.
