### ISSUE TITLE
Documentation innacuracy

### ISSUE THREAD

**Issue by drzel** [cloudinary/cloudinary_gem#215]
The ruby code snippet given for scaling an image to a height of 200 pixels at: http://cloudinary.com/documentation/image_transformations#image_scaled_to_a_height_of_200_pixels is given as:

`cl_image_tag("sample.jpg", :height=>200)`

However this will not scale the image as the crop attribute is not given. As mentioned at: http://cloudinary.com/documentation/rails_image_manipulation#resize_crop_and_thumbnails

> Note that you must provide the :crop parameter, for the resize or crop transformation to take effect. Without it, the image will be downloaded at its original dimensions and the browser will end up stretching or shrinking it on the client's side.

**Comment by roeeba** [comment]
@drzel: This is indeed an inaccuracy we will fix soon. Thank you for taking the time to report!

**Comment by drzel** [comment]
@roeeba No worries.

These ones look to be innacurate too:

`cl_image_tag("sample.jpg", :width=>200, :height=>100)`
`cl_image_tag("sample.jpg", :width=>0.5)`

**Comment by roeeba** [comment]
@drzel: We will make sure to update all relevant sample codes. Thanks again.

**Comment by dwbutler** [comment]
Another one here: http://cloudinary.com/documentation/image_transformations#sample_image_using_the_crop_face_detection_rounded_corners_and_resize_features

```ruby
cl_image_tag("lady.jpg", :transformation=>[
  {:width=>400, :height=>400, :gravity=>"face", :radius=>"max", :crop=>"crop"},
  {:width=>200}
  ])
```

Should be

```ruby
cl_image_tag("lady.jpg", :transformation=>[
  {:width=>400, :height=>400, :gravity=>"face", :radius=>"max", :crop=>"crop"},
  {:width=>200, crop: 'scale'}
  ])
```

**Comment by roeeba** [comment]
Hi @dwbutler: Thank you, we are working on fixing this on all related samples. Sorry for your inconvenience.

**Comment by roeeba** [comment]
The issue had been fixed and the `crop` attribute has been added across our documentations. Thank you for reporting this.
