### ISSUE TITLE
CarrierWare image dimension (wigth, height) on nested model? 

### ISSUE THREAD

**Issue by Pedroknoll** [cloudinary/cloudinary_gem#216]
I followed the faq to retrieve image dimensions but this is not working (https://support.cloudinary.com/hc/en-us/articles/202519822-How-to-retrieve-image-dimensions-when-uploading-to-Cloudinary-using-CarrierWave-)

I have a merchant model that accepts_nested_attributes for images as:

`class Merchant < ApplicationRecord
  has_many   :images, inverse_of: :merchant, dependent: :destroy
  accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true
end`

My image model

```
class Image < ApplicationRecord
   belongs_to :merchant

  mount_uploader :image, ImageUploader
  after_save :update_dimensions 

 def update_dimensions 
  if self.image.present? && self.image.metadata.present? 
    width = self.image.metadata["width"] 
    height = self.image.metadata["height"] 
  end 
end 
end
```

At the Merchant Controller I added to the Strong Parameters the width and height image attributes.

But the width and height are showed as null. Any idea?

**Comment by taragano** [comment]
Hi @Pedroknoll,
Does it work for you for non-nested models?

While we don't currently don't have a code example of nested models, here's a basic sample project the demonstrates a non-nested model:
https://github.com/taragano/Rails_retrieve_image_data

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.
