### ISSUE TITLE
Downloading a private, raw file?

### ISSUE THREAD

**Issue by milesmatthias** [cloudinary/cloudinary_gem#218]
I've uploaded a private, raw file (a CSV) and want to download it on our server to do some processing. I see I can do something like this to generate a url:

```ruby
url = Cloudinary::Utils.private_download_url(public_id, format)
```

and then use the downloader:

```ruby
download = Cloudinary::Downloader.download(url)
```

but no matter what `format` I use (csv, raw, auto, etc.) I get:

```
"{\"error\":{\"message\":\"Invalid extension in transformation: auto\"}}"
```

What do I need to be using here to download the file?

**Comment by taragano** [comment]
Hi @milesmatthias,

Please try the following:

```
url = Cloudinary::Utils.private_download_url(public_id, format, resource_type: :raw)
download = Cloudinary::Downloader.download(url)
```

**Comment by milesmatthias** [comment]
@taragano Thanks! Now I'm getting a (probably) unrelated error, so after I resolve that this should work.
