### ISSUE TITLE
Passing headers to Cloudinary when uploading

### ISSUE THREAD

**Issue by juliaramstedt** [cloudinary/cloudinary_gem#220]
Hi,

I'm trying to add a "X-Robots-Tag: noindex" header to my files when uploading.

They can be passed with options when using: Cloudinary::Uploader.upload(file, options = {}).

I'm using Cloudinary and CarrierWave by including Cloudinary::Carrierwave in a custom uploader class. Is there any way of adding options to the upload method?

Thanks!

**Comment by taragano** [comment]
If you perform client-side uploads, you can do something like the following in your form (for signed uploads):

```
<%= form_for(@mymodel) do |f| %>
  ...
  <%= f.cl_image_upload(:image, headers: "X-Robots-Tag: noindex") %>
  ...
<% end %>
```

For server-side uploads, you can do something like the following in your uploader:

```
class ImageUploader < CarrierWave::Uploader::Base
  include Cloudinary::CarrierWave

  process cloudinary_transformation headers: "X-Robots-Tag: noindex"
  ...
end
```

**Comment by juliaramstedt** [comment]
Works perfectly! Thanks!
