### ISSUE TITLE
Dynamic Resize with Cloudinary

### ISSUE THREAD

**Issue by kntmrkm** [cloudinary/cloudinary_gem#224]
My env is...

- rails 5.0.1
- carrierwave 0.11.2
- cloudinary 1.3.0

I want to resize depend on model like below.

```
class PostImageUploader < ImageUploader
  include Cloudinary::CarrierWave

  process dynamic_resize: :standard

  def dynamic_resize
    raise unless account = model.try(:account)
    raise unless account_setting = account.try(:setting)

    image_height = account_setting.post_image_height.to_i
    image_width = account_setting.post_image_width.to_i

    resize_to_fit *(dynamic_size)
end
```

Original method `dinamic_resize` works well without `Cloudinary::CarrierWave`.
But, I have no idea to accomplish that with cloudinary.

Any idea?

**Comment by nadavofi** [comment]
Hi, check out this suggested solution:
https://support.cloudinary.com/hc/en-us/articles/202519822-How-to-retrieve-image-dimensions-when-uploading-to-Cloudinary-using-CarrierWave-
Does this help you on your use-case?

**Comment by kntmrkm** [comment]
Hi, thanks for suggestion.
The article's method make image as too small size(low quality).

I want to keep quality with intended size.

e.g) 5MB 3200x2400 => 100KB 900x300 (almost same quality for human)

So, I will try to found another way.

thanks!

**Comment by nadavofi** [comment]
You can use the quality flag to determine how much the output image is compressed. Use quality:auto to get an optimal result.
See: http://cloudinary.com/documentation/image_transformations#automatic_quality_and_encoding_settings

Feel free to [open a support ticket](https://support.cloudinary.com/hc/en-us/requests/new) with more details regarding your specific use case and concerns and we'll be happy to assist further.
