### ISSUE TITLE
Upload using Cloudinary::Uploader and use response to save carrierwave instance

### ISSUE THREAD

**Issue by thebucknerlife** [cloudinary/cloudinary_gem#228]
Hi,

I'd like to upload files through my Rails app using `Cloudinary::Uploader`. Then I'd like to take the response of that call and use it (maybe the `public_id`?) to attach the upload as an image attachment via Carrierwave.

I tried using `remote_image_url`, `Cloudinary::CarrierWave::StoredFile` and `Cloudinary::CarrierWave::CloudinaryFile`.

Is there some way to save a cloudinary image upload as a carrierwave file attachment?

I want handle the upload to carrierwave by hand because I have some custom React doing the upload. So I can't use any of the cloudinary view helpers or JS helpers.

Thanks!

**Comment by taragano** [comment]
Cloudinary's GEM seamlessly integrates with CarrierWave, actually all of this automatically happens behind the scenes, and is already being taken care of.
Please see our Rails+CarrierWave+Cloudinary sample project:
https://github.com/cloudinary/cloudinary_gem/tree/master/samples/photo_album

**Comment by taragano** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support http://support.cloudinary.com or [create a new ticket](https://support.cloudinary.com/hc/en-us/requests/new) if you have any additional issues.

**Comment by thanhtruong1216** [comment]
After hours of digging into this issue. Here is the fix: https://stackoverflow.com/a/50767069/9516571
