### ISSUE TITLE
Demo for mongoid wanted

### ISSUE THREAD

**Issue by mediatainment** [cloudinary/cloudinary_gem#25]
I came around and wanna know if mongoid is supported.
All examples of cloudinary are only ActiveRecord based.
Also on the website of cloudinary.com I did not found any word about mongoid.

Can you provide a "simple setup" or "Demo App" for using 
* cloudinary-carrierwave-mongoid or 
* cloudinary-mongoid

At this time my setup looks like this:

    class ImageUploader < CarrierWave::Uploader::Base
      include Cloudinary::CarrierWave
          def cache_dir
            "#{Rails.root}/tmp/uploads"
          end
          version :thumb do
            process :resize_to_fit => [200, 200]
          end
          def public_id
             return model.location_image_id
          end

Class Location

     class Location
        include Mongoid::Document
        mount_uploader :image, ImageUploader

YML Config File exists.

Saving on Cloudinary does not work, but on my local file-system 

Any help?

Thanks

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
