### ISSUE TITLE
rail helper generates wrong link when passing negative position arg

### ISSUE THREAD

**Issue by ninjarabbi** [cloudinary/cloudinary_gem#250]
This:
`cl_image_tag('squvi6lcu9freqnyqvfb', transformation: [{overlay: 'play_overlay', width: 150, y: -10, crop: 'scale'}])`

produces this, which doesn't work:
http://res.cloudinary.com/<my_cludinary_id>/image/upload/c_scale,l_play_overlay,w_150,**y_sub10**/squvi6lcu9freqnyqvfb

This works:
http://res.cloudinary.com/<my_cludinary_id>/image/upload/c_scale,l_play_overlay,w_150,**y_-10**/squvi6lcu9freqnyqvfb

It generates y_sub10 instead of y_-10. I just had this happen to me in production unexpectedly after updating the gem from 1.3 to 1.6.

**Comment by ehoch** [comment]
Can confirm. Rolling back to 1.5.2 fixes this. Looks like the problem commit was:

https://github.com/cloudinary/cloudinary_gem/commit/e49dfa69bc8708db5ae3a2cf816b146a14ff1581

**Comment by taragano** [comment]
Thank you for reporting about this. I'm passing this on to our team.
Updates to follow

**Comment by tocker** [comment]
This was fixed in version 1.7.0.

@ninjarabbi can you please confirm it solved your issue?

**Comment by ninjarabbi** [comment]
yeah it's fixed, thanks
