### ISSUE TITLE
Unable to Seed Image Data for Development

### ISSUE THREAD

**Issue by trendwithin** [cloudinary/cloudinary_gem#251]
Ruby 2.3.1, Rails 5.0.2, Carrierwave 1.0, Cloudinary 1.6

I can verify Cloudinary uploads images and works as expected running Rails locally, however I can neither seed with a working url nor save a record through the console without the field being blank.  If I go so far as to require the presence: `ActiveRecord::RecordInvalid: Validation failed: Main image can't be blank`

If I comment out `mount_uploader` then my data will seed and is viewable when I run Rails locally.

**Comment by roeeba** [comment]
Hi @trendwithin, Can you please share the exact code that you're trying to seed with? Does the image already exists on your Cloudinary account and you just need to seed it into the DB, or do you need to upload a new image prior to the seeding?

**Comment by trendwithin** [comment]
@roeeba  I used the url from the image I was able to upload to Cloudinary running locally and can also verify success after deploying to Heroku.  I believe it is safe to assume that my set up and configuration works as expected.  The issue I'm currently tackling is seeding without having to comment out `mount_uploader`.

```
  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader
```

In the console I created a new record four times and documented the output.  As can be noted, when I comment out `mount_uploader` a new record has the url, but when uncommented the result is nil.

``` 
  # mount_uploader :thumb_image, PortfolioUploader
  # mount_uploader :main_image, PortfolioUploader

irb(main):048:0> Folio.new(title: 'Test', body: 'Test One', position: 1, main_image: 'image/upload/v1491101349/pdsaq8dmyvnhnh2uuxw8.jpg', thumb_image: 'image/upload/v1491101347/xfso3mgb0mydlci05bgr.jpg')
=> #<Folio id: nil, title: "Test", subtitle: nil, body: "Test One", main_image: "image/upload/v1491101349/pdsaq8dmyvnhnh2uuxw8.jpg", thumb_image: "image/upload/v1491101347/xfso3mgb0mydlci05bgr.jpg", created_at: nil, updated_at: nil, position: 1>
```

```
  mount_uploader :thumb_image, PortfolioUploader
  # mount_uploader :main_image, PortfolioUploader

irb(main):049:0> reload!
Reloading...
=> true
irb(main):050:0> Folio.new(title: 'Test', body: 'Test One', position: 1, main_image: 'image/upload/v1491101349/pdsaq8dmyvnhnh2uuxw8.jpg', thumb_image: 'image/upload/v1491101347/xfso3mgb0mydlci05bgr.jpg')
=> #<Folio id: nil, title: "Test", subtitle: nil, body: "Test One", main_image: "image/upload/v1491101349/pdsaq8dmyvnhnh2uuxw8.jpg", thumb_image: nil, created_at: nil, updated_at: nil, position: 1>
```

```
  # mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

irb(main):051:0> reload!
Reloading...
=> true
irb(main):052:0> Folio.new(title: 'Test', body: 'Test One', position: 1, main_image: 'image/upload/v1491101349/pdsaq8dmyvnhnh2uuxw8.jpg', thumb_image: 'image/upload/v1491101347/xfso3mgb0mydlci05bgr.jpg')
=> #<Folio id: nil, title: "Test", subtitle: nil, body: "Test One", main_image: nil, thumb_image: "image/upload/v1491101347/xfso3mgb0mydlci05bgr.jpg", created_at: nil, updated_at: nil, position: 1>
irb(main):053:0>
```

```
  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

irb(main):053:0> reload!
Reloading...
=> true
irb(main):054:0> Folio.new(title: 'Test', body: 'Test One', position: 1, main_image: 'image/upload/v1491101349/pdsaq8dmyvnhnh2uuxw8.jpg', thumb_image: 'image/upload/v1491101347/xfso3mgb0mydlci05bgr.jpg')
=> #<Folio id: nil, title: "Test", subtitle: nil, body: "Test One", main_image: nil, thumb_image: nil, created_at: nil, updated_at: nil, position: 1>
```

**Comment by roeeba** [comment]
Hi @trendwithin, thanks for the detailed response. 
1.  It's actually okay that you see the `nil` value. These fields are updated after the record is saved to the DB.
2. Initializing the fields with a partial identifier (e.g., `image/upload/v1491101347/xfso3mgb0mydlci05bgr.jpg`) won't work. Our GEM also validates the upload by checking the signature, so you'll need to have a full identifier, which also includes the signature. You can do something like the following:

```
def full_identifier(image)
  params = {version: image.file.version, public_id: image.file.public_id}
  signature = Cloudinary::Utils.sign_request(params)[:signature]
  image.file.identifier + '#' + signature
end

current_folio = Folio.find(:id) 
main_image = full_identifier(current_folio.main_image)
thumb_image = full_identifier(current_folio.thumb_image)

new_folio = Folio.new(title: 'Test', body: 'Test One', position: 1, main_image: main_image, thumb_image: thumb_image)
new_folio.save
```

**Comment by trendwithin** [comment]
Apologies... for whatever reason my response to you three days back didn't stick.  Apparently trying to `Close and comment` to my own thread failed... anyways, after inspecting what is retuned I better understand what's happening behind the scenes with the additional data  that I wasn't aware of.  Thank you for taking the time to inform me...

**Comment by roeeba** [comment]
Thanks for the update, @trendwithin. Glad I ould help :)
I'll close this ticket now, but feel free to reach out if you have any further questions regarding this matter.
