### ISSUE TITLE
`NoMethodError` when using `CarrierWave::ActiveRecord#mount_uploaders`

### ISSUE THREAD

**Issue by linterpreteur** [cloudinary/cloudinary_gem#252]
After some hard time, I found that the problem was the following code snippet.

```ruby
uploader = self.model.send(self.mounted_as)
```

You can find it in [carrier_wave.rb](https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/carrier_wave.rb#L211) and [process.rb](https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/carrier_wave/process.rb#L147).

Because `self.model.mounted_as.is_a?(Array)`, methods that would have been called on `Uploader` objects gets called on `Array`'s.  Adding `uploader = uploader[0] if uploader.is_a?(Array)` after each line was enough in my case.

Please let me know if you need more details. Thanks!

**Comment by taragano** [comment]
Thanks @linterpreteur :)
I've passed it on to our team to have a look.
