### ISSUE TITLE
CloudinaryException (Must supply api_key) in production environment

### ISSUE THREAD

**Issue by TeddySmoker** [cloudinary/cloudinary_gem#254]
- NGINX v1.10.2
- Puma v3.8.2
- Ruby v2.3.1p112 (2016-04-26 revision 54768)
- Rails v4.2.5
- Cloudinary v1.7.0

Hello,

I am encountering a very, if I may say so, strange error on a Ubuntu 16.04 Linode VPS server. 
Whenever I try using the Cloudinary gem it fails with this exception (see title). 

I've setup cloudinary.yml as described in the documentation, I've also tried using a cloudinary.rb initializer. 

The strange part is that it only fails in production on the Ubuntu server but not while running it in production mode on my local machine. 

I am using Figaro to store the authentication details but I've also tried hard-coding the auth. details in the .yml and initializer (note: I am not using the cloudinary.yml and initializer file in the same time)

Edit: spelling

**Comment by TeddySmoker** [comment]
Here are some screenshots. 

![initializer](https://cloud.githubusercontent.com/assets/16388688/25019899/9fe2563c-208c-11e7-9a78-f22006f8b702.png)
cloudinary.rb

![puma-log](https://cloud.githubusercontent.com/assets/16388688/25019905/a9615668-208c-11e7-8b81-b48ceb2224ff.png)
puma log in production 

![rails-console](https://cloud.githubusercontent.com/assets/16388688/25019914/b03a4c2e-208c-11e7-9af7-dbae918463ff.png)
rails console in production

**Comment by TeddySmoker** [comment]
Hello.

I am back with a fix to my problem.
It wasn't related to Cloudinary or Figaro, but to Capistrano.

I forgot to symlink application.yml (the one generated by Figaro) and this is why it wasn't functioning as expected.

I will now close this issue.

**Comment by farkroft** [comment]
how you fix that issue, give me some help

**Comment by idobarnoam** [comment]
Hi @farkroft,

It looks like the user who opened the issue is deleted.

It also seems that the issue is not Cloudinary related, so I'm not sure how we can further help.

Perhaps trying the last suggestion that the user who opened the request added might help.

Thanks,
Ido
