### ISSUE TITLE
Still getting 

### ISSUE THREAD

**Issue by alopez25** [cloudinary/cloudinary_gem#262]
Still getting an stopper when running my server using cloudinary_gem v1.2.4 with Rails 5.1.2. I thought it was fixed [here](https://github.com/cloudinary/cloudinary_gem/issues/211) but it seems it is not the case. 

`cloudinary-1.2.4/lib/cloudinary/helper.rb:272:in `block in included': undefined method `alias_method_chain' for ActionView::Base:Class (NoMethodError)`

**Comment by roeeba** [comment]
Hi @alopez25, can you please update your Cloudinary GEM to the latest version (1.8.1) and let us know if you still have an issue? if so, please share with us the code responsible for error along with the full error stacktrace.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
