### ISSUE TITLE
Doesn't work with carrierwave multiple file uploads

### ISSUE THREAD

**Issue by epoberezhny** [cloudinary/cloudinary_gem#266]
Doesn't work with carrierwave multiple file uploads

**Comment by taragano** [comment]
It's on our road-map to fully support multiple assignments with CarrierWave. In the meantime, you can accomplish that with a different approach. Here's a sample project: 
https://github.com/taragano/Cloudinary_multiple_uploads

**Comment by vcavallo** [comment]
It was an unpleasant surprise to find that `cloudinary_gem` doesn't work with carrierwave multiple files - and while your sample project is really helpful and appreciated, it's a bit of a bummer to have to set up additional associations I didn't exactly want.
so: thanks for the sample project! and: hopefully this gem will support multiple files soon!

**Comment by roeeba** [comment]
Hi, @vcavallo. 
Sorry we couldn't help further. 
We will update here once this is supported.

**Comment by vcavallo** [comment]
@roeeba I'd might be interested in helping out, if you think that could be useful.

**Comment by roeeba** [comment]
Thanks, @vcavallo, really appreciated! 
At the moment, no help is needed. We will update otherwise.

**Comment by thomasbromehead** [comment]
Hi guys,
Where are with this feature, I spent a good hour figuring out what was happening today...

**Comment by yakirp** [comment]
Hi @thomasbromehead ,

We're sorry but it's still on our roadmap to support it, no eta yet.

--Yakir

**Comment by const-cloudinary** [comment]
Fixed in #501

**Comment by vcavallo** [comment]
Nice! You made a promise and kept it :)
