### ISSUE TITLE
Cloudinary::Api::Response breaks active_support's Hash extensions

### ISSUE THREAD

**Issue by hayduke19us** [cloudinary/cloudinary_gem#274]
SEE: PR #273

**Comment by strausr** [comment]
Hi, @hayduke19us. Thank you for reporting this. Our dev team will review this, we will update as soon as we have any insights.

**Comment by hayduke19us** [comment]
Thanks @strausr!

**Comment by bascht** [comment]
Looks like #273 is merged, I think @strausr can safely close this one. 😸
