### ISSUE TITLE
Cloudinary / Rails / EngineYard only works first time

### ISSUE THREAD

**Issue by newfylox** [cloudinary/cloudinary_gem#276]
Hi!

I've followed every step to configure this gem with my EngineYard hosting plan. It could be the environment variable or it could be the `cloudinary.yml` file, it's always the same issue.

The first time I run the application, I can see my images with RailsAdmin, CarrierWave on my Model. But when I refresh the page or edit a model, it crashes saying that `cloud_name` is not defined.

**`CloudinaryException: Must supply cloud_name in tag or in configuration`**

I don't understand because the first time I access the RailsAdmin model page, it works, but after it always crashes. When My mobile application asks my Rails API server to serialize my model, it crashes too.

Seems like it's only define the first time at booting and then gone for a second access.

Thanks

**Comment by shirlymanor** [comment]
The `Must supply cloud_name in tag or in configuration` message usually means that the Cloudinary library doesn't have your account properly configured, so it doesn't know which Cloudinary account to work with.
You can globally configure your account, as explained [here](https://cloudinary.com/documentation/rails_integration#configuration).

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
