### ISSUE TITLE
Different image_metadata for same file on upload and on api request

### ISSUE THREAD

**Issue by dmitry-fedorov** [cloudinary/cloudinary_gem#277]
Hi

I'm trying to retrieve ```image_metadata``` from response on upload:
1. The image_metadata that I'm receiving from [this](https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/uploader.rb#L323) request:

```"image_metadata":{"JFIFVersion":"1.01","ResolutionUnit":"None","XResolution":"1","YResolution":"1","Colorspace":"RGB","DPI":"0"}``` 

```params``` are default except ```:image_metadata=>1, :transformation=>"c_limit,h_5000,w_5000"```

2. The image_metadata that I'm receiving from that request ```Cloudinary::Api.resource(public_id, image_metadata: true)```

```"image_metadata": {"JFIFVersion":"1.01", "ResolutionUnit":"inches", "XResolution":"150", "YResolution":"150", "Colorspace":"RGB", "DPI":"150"}```

I'm 100% sure that ```public_id``` is the same for both cases.
The [image](https://drive.google.com/file/d/1nx5X8FasjCYxr7C78p8dMihz8zM4SKLT) .

We've already asked cloudinary support about that one and all seems fine when we doing that through cloudinary web interface.

Also note that after uploading on cloudinary link we have different image (the original one was 278kB, the uploaded one - 162kB)

Thank you.

**Comment by roeeba** [comment]
Hi @dmitry-fedorov, apologies for the late reply. We've managed to reproduce this inconsistency on our end as well. There's indeed a difference in the `image_metada` output when checking an uploaded resource with incoming transformations vs checking a derived resource with the same transformation. Our team is checking it now. We will update ASAP.

**Comment by roeeba** [comment]
UPDATE - Issue has been fixed.
