### ISSUE TITLE
Syntax error in ruby doco

### ISSUE THREAD

**Issue by zenspider** [cloudinary/cloudinary_gem#279]
in the migration section:

```ruby
  :complete=>proc{|id|, result| $stderr.print "done #{id} #{result}\n" }
```

should be:

```ruby
  :complete=>proc{|id, result| $stderr.print "done #{id} #{result}\n" }
```

**Comment by strausr** [comment]
@zenspider Can you please share with us where you found the syntax error?

**Comment by zenspider** [comment]
can't you grep for it?

**Comment by zenspider** [comment]
Found it

https://cloudinary.com/documentation/rails_additional_topics#migration

**Comment by strausr** [comment]
@zenspider Thanks!

**Comment by zenspider** [comment]
Please fix these issues.

**Comment by strausr** [comment]
@zenspider This will be fixed in the next release.

**Comment by strausr** [comment]
@zenspider This was fixed. Closing.
