### ISSUE TITLE
`jpeg` no longer identified as a valid image type

### ISSUE THREAD

**Issue by diazruy** [cloudinary/cloudinary_gem#280]
It appears that in [v1.1.3](https://github.com/cloudinary/cloudinary_gem/commit/65b79c87f0bc2f33fb0c25f8a54d5c67faf8d223#r26772859) `jpeg` was removed from the list of [`IMAGE_FORMATS`](https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/utils.rb#L699). It appears that there is some sort of support for [aliases](https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary.rb#L54), but these don't seem to be used [when figuring out the `resource_type_for_format`](https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/utils.rb#L717). Without `jpeg` in the list of `IMAGE_FORMATS`, urls generated by the gem end up with `/raw/` in the path instead of `/image/`.

**Comment by d-mendoza** [comment]
Hi @diazruy 

Can you please provide the steps to reproduce the issue and if you have an example image (extension "jpeg") that we can use, that would be helpful.

**Comment by diazruy** [comment]
@d-mendoza I am using the Carrierwave integration. I have an existing model pointing to a URL with `jpeg` extension (the `image` atttribute has `"property-agent/image/V33836/7605_2891_melissa_Wu.jpeg"`. When I ask the model for `model.image.url`, the output is https://res-1.cloudinary.com/grieg-dev/raw/upload/v1/property-agent/image/V33836/7605_2891_melissa_Wu.jpeg

When requesting that path, it does indeed serve the correct image from Cloudinary, however the "malformed" URL (which previously in v 1.1.2 returned `/image/upload/...` instead of `/raw/upload`) is causing issues in other parts of the application where we parse the URL and are expecting a path with `image` instead of `raw`. 

Was there a particular reason why `jpeg` was removed from the list of `IMAGE_FORMATS`? Looks like other formats with aliases (e.g. `tif` and `tiff` , as well as `jpe`) were maintained, but only `jpeg` got removed, which I think might have been accidental.

**Comment by diazruy** [comment]
FWIW re-adding `jpeg` to the list of `IMAGE_FORMATS` resolves the issue and restores the original behaviour from v1.1.2

**Comment by d-mendoza** [comment]
We have been unable to reproduce it and it could be because it was uploaded a while ago. We are wondering if you could reproduce this issue on the latest gem version with a brand new jpeg upload.

**Comment by diazruy** [comment]
Uploading a new image does indeed set the extension to `.jpg`. However, we have a number of existing assets (uploaded by customers) which are `.jpeg` for which the incorrect URL is being generated. Could you maybe expand on why the support for `jpeg` extension was removed, while still maintaining it for `.jpe` and `.tiff` so I can maybe better understand? Barring restoring the previous behaviour (which you seem to support for other formats), would the only solution for us be to manually update out database to rename all `.jpeg` files to `.jpg`?

**Comment by diazruy** [comment]
By the way, I was trying to fork the project to submit a pull request, but I am unable to run the tests as described [here](https://github.com/rew-ca/cloudinary_gem/blob/master/CONTRIBUTING.md), running into what seems to be some missing configuration
````
Cloudinary::Api::AuthorizationRequired:
  unknown api_key
...
     CloudinaryException:
       Must supply api_key
...
      CloudinaryException:
        Invalid api_key key
```
But I don't see any additional configuration instructions in the guide. Any idea?

**Comment by d-mendoza** [comment]
@diazruy Thank you for reporting that. I am running it by our dev team. Updates to follow.

As for your second question, to run the tests, an environment variable would need to be added.
`export CLOUDINARY_URL=cloudinary://<api_key>:<api_secret>@<cloud_name>`. 

The environment variable can be retrieved from your Cloudinary dashboard (https://cloudinary.com/console).

**Comment by diazruy** [comment]
@d-mendoza  The file would have likely been uploaded with v1.1.0 of the gem

```ruby
development (main):0 > a.image
=> #<Property::AgentImageUploader:0x0000556ea85e56c0
 @file=
  #<Cloudinary::CarrierWave::CloudinaryFile:0x0000556ea85e5698
   @filename="property-agent/image/V33836/7605_2891_melissa_Wu.jpeg",
   @format="jpeg",
   @identifier="property-agent/image/V33836/7605_2891_melissa_Wu.jpeg",
   @public_id="property-agent/image/V33836/7605_2891_melissa_Wu",
   @resource_type="raw",
   @storage_type=nil,
   @uploader=#<Property::AgentImageUploader:0x0000556ea85e56c0 ...>,
   @version=nil>,
 @model=
  #<Property::Agent:0x0000556ea8160668
   [snip]
   image: "property-agent/image/V33836/7605_2891_melissa_Wu.jpeg",
   [snip]
   >,
 @mounted_as=:image,
 @original_filename="property-agent_image_V33836_7605_2891_melissa_Wu.jpeg",
 @public_id="property-agent/image/V33836/7605_2891_melissa_Wu",
 @stored_public_id="property-agent/image/V33836/7605_2891_melissa_Wu",
 @stored_version=nil>

development (main):0 > a.image.file
=> #<Cloudinary::CarrierWave::CloudinaryFile:0x0000556ea85e5698
 @filename="property-agent/image/V33836/7605_2891_melissa_Wu.jpeg",
 @format="jpeg",
 @identifier="property-agent/image/V33836/7605_2891_melissa_Wu.jpeg",
 @public_id="property-agent/image/V33836/7605_2891_melissa_Wu",
 @resource_type="raw",
 @storage_type=nil,
 @uploader=
  #<Property::AgentImageUploader:0x0000556ea85e56c0
   @file=#<Cloudinary::CarrierWave::CloudinaryFile:0x0000556ea85e5698 ...>,
   @model=
    #<Property::Agent:0x0000556ea8160668
     [snip]
     image: "property-agent/image/V33836/7605_2891_melissa_Wu.jpeg",
     [snip]
     >,
   @mounted_as=:image,
   @original_filename="property-agent_image_V33836_7605_2891_melissa_Wu.jpeg",
   @public_id="property-agent/image/V33836/7605_2891_melissa_Wu",
   @stored_public_id="property-agent/image/V33836/7605_2891_melissa_Wu",
   @stored_version=nil>,
 @version=nil>

```

**Comment by d-mendoza** [comment]
@diazruy 
Thank you for getting that information.
We have been unable to produce the issue as it appears that the storage_type and version are showing unexpected values. However, we have came up with a potential workaround that should fix those resources, I have added the same code below:

```ruby
image = a.image
public_id = "property-agent/image/V33836/7605_2891_melissa_Wu" # preferably a.my_public_id (if not nil, and it needs to exclude the extension)

version = 1442506910 # preferably a.version (if not nil)

#in case a.version is nil, do the following two lines instead
resource = Cloudinary::Api.resource(public_id)
version = resource["version"]

signature = Cloudinary::Utils.api_sign_request({:public_id=>public_id, :version=>version}, Cloudinary.config.api_secret)
identifier = "image/upload/v#{version}/#{public_id}.jpeg##{signature}"
a.update_attribute("image", identifier)
```

**Comment by kimihito** [comment]
I had the same problem using Ruby on Rails, So I added below code as  `config/initializers/cloudinary.rb` .  ( Maybe this way is not good...  😓 )

```code:config/initializers/cloudinary.rb

Cloudinary::Utils::IMAGE_FORMATS.append('jpeg')

```

**Comment by aleksandar-cloudinary** [comment]
Hi @kimihito jpeg was getting normalised on uploads to jpg and to complete this it process it was removed from image formats. Were you able to use Daniel's suggestion to update those records that have been uploaded using the older gem version?
