### ISSUE TITLE
The config that reads ENV["CLOUDINARY_CLOUD_NAME"] seems unclear and silently dangerous

### ISSUE THREAD

**Issue by benhalpern** [cloudinary/cloudinary_gem#285]
If I want to configure my app using an initializer that makes use of environment variables I can do so, but the app _also_ directly reads from environment variables themselves. This behavior seems confusing.

```
if first_time && ENV["CLOUDINARY_CLOUD_NAME"]
      set_config(
        "cloud_name"          => ENV["CLOUDINARY_CLOUD_NAME"],
        "api_key"             => ENV["CLOUDINARY_API_KEY"],
        "api_secret"          => ENV["CLOUDINARY_API_SECRET"],
        "secure_distribution" => ENV["CLOUDINARY_SECURE_DISTRIBUTION"],
        "private_cdn"         => ENV["CLOUDINARY_PRIVATE_CDN"].to_s == 'true',
        "secure"              => ENV["CLOUDINARY_SECURE"].to_s == 'true'
      )
    elsif first_time && ENV["CLOUDINARY_URL"]
      config_from_url(ENV["CLOUDINARY_URL"])
    end
```

I could potentially create an environment variable called `CLOUDINARY_CLOUD_NAME` without being aware that the gem is configuring itself based off of that and then be stuck _without_ the rest of my config because I didn't purposefully create all the variables as such.

**Comment by roeeba** [comment]
Hi @benhalpern. Thank you for the feedback. 
Note that configuring SDKs by setting environment variables is a common pattern on many SDKs. 
We'll make sure to add this to our documentation to avoid confusions.
