### ISSUE TITLE
migrator completely broken if you’re not using carrierwave

### ISSUE THREAD

**Issue by zenspider** [cloudinary/cloudinary_gem#286]
There’s no tests for this thing?!?

I changed the code to provide extra checks so rails won’t forcibly load any of the carrier_wave files you have that then expect carrier_wave to be extant.

```ruby
elsif defined?(::CarrierWave) && defined?(Cloudinary::CarrierWave) && data.is_a?(Cloudinary::CarrierWave)
#     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by roeeba** [comment]
Hi @zenspider. Thanks for pointing it out! I've opened a ticket for our dev engineers. We will update as soon as this is resolved.
