### ISSUE TITLE
migrator logging should use mutex

### ISSUE THREAD

**Issue by zenspider** [cloudinary/cloudinary_gem#287]
otherwise it just writes all over itself.

**Comment by roeeba** [comment]
Hi @zenspider. `$stderr.print`, which we use to write logs, is supposedly atomic, meaning that each log should be in its own line. Can you please share an example debug output that demonstrates your claim?

**Comment by zenspider** [comment]
I’ve never seen documentation or code to that effect. What gave you that idea? `IO.sync` is not the same thing as thread synchronization.

**Comment by roeeba** [comment]
Hi @zenspider. To better understand the issue you're raising, could you please help by providing a debug output or a sample code that reproduces it? thanks!

**Comment by zenspider** [comment]
Using your code reproduces it. Simple as that. There’s nothing “atomic” about any of the IOs in ruby unless you wrap it yourself. Not sure why you’re not trusting me on this. Don’t make a claim if you can’t back it up by at least pointing to documentation. Here’s some of my current output... But asking for me to reproduce something that is inherently non-deterministic is a problematic way of going about technical support:

```
{33=>nil}
2018-02-22 12:45:48 -0800 Cloudinary::Migrator Thread 6 - processing row {"internal_id"=>32, "url"=>nil, "public_id"=>nil, "metadata"=>"{}", "status"=>"processing", "updated_at"=>1519332348, "id"=>16}. 0 work waiting. 0 results waiting.
2018-02-22 12:45:48 -0800 Cloudinary::Migrator35=>nil}{31=>nil}
 Process: {:id=>36}
2018-02-22 12:45:48 -0800 Cloudinary::Migrator Process: {:id=>38}
2018-02-22 12:45:48 -0800 Cloudinary::Migrator Process: {:id=>37}
2018-02-22 12:45:48 -0800 Cloudinary::Migrator Process: {:id=>39}
32=>nil}
2018-02-22 12:45:48 -0800 Cloudinary::Migrator Process: {:id=>40}
2018-02-22 12:45:48 -0800 Cloudinary::Migrator Thread 5 - processing row {"internal_id"=>34, "url"=>nil, "public_id"=>nil, "metadata"=>"{}", "status"=>"processing", "updated_at"=>1519332348, "id"=>17}. 4 work waiting. 1 results waiting.
2018-02-22 12:45:48 -0800 Cloudinary::Migrator Done ID=31, result={"error"=>{"message"=>"Empty data and url", "http_code"=>404}}
```

**Comment by roeeba** [comment]
Hi @zenspider. Thanks for the heads up. We’ll investigate this further and introduce a fix if needed.

**Comment by zenspider** [comment]
This is a 2 line change and I’ve shown above how it is needed.

**Comment by roeeba** [comment]
Hi @zenspider. Thank you for the PR, appreciated. The part which wraps `$stderr` with a mutex and the part which checks if CarrierWave exists in the project seems fine.
The part which deals with the `vendor/assets` should be removed as there's an alternative way of fixing the problem you're facing (see my comment on #291). We prefer not to persist the static assets as part of the repository.

**Comment by tocker** [comment]
Hi @zenspider, for thoroughness' sake I'm trying to understand where the messy printing is coming from. `{33=>nil}` Does not seem to come from any of the `debug()` lines in `Migrator`.
Since we are using the single string arg form of print with a new line, the underlying `io.write` should flush the stream.
You are right that this is not documented in the Ruby documentation but rather an implementation detail.

I'd appreciate it if you could share the code your using to invoke the Migrator. If your are modifying the stderr in any way (e.g. redirection), please include that detail too.

**Comment by zenspider** [comment]
> Since we are using the single string arg form of print with a new line, the underlying io.write should flush the stream.

Claims of atomicity and resilience to threads with no proof to back it up... Over a 2 line change for a mutex you already provide... I've shown there is a problem. I've shown that the mutex cleans it up. I don't see why there's *any* push back here. I'm not going to provide a repro for something that is nondeterministic yet so trivial.

Buggy online doco. Non-existant sample code. No tests. Missing requires. Trailing whitespace EVERYWHERE, Non-idiomatic ruby. **There is so much to be improved here**, but you're pushing back on a mutex around debug logging.

I'm getting really tired of this guys. Even if it is for "thoroughness' sake".
