### ISSUE TITLE
Missing vendor/assets

### ISSUE THREAD

**Issue by zenspider** [cloudinary/cloudinary_gem#291]
Means you can’t use this with a forked git checkout in your Gemfile?

Is there a way to do this? I’ve got a PR open and until that goes live, we need to have these fixes in place. Unfortunately all our rendered tests fail with:

```
 29) Error:
UsersControllerTest#test_welcome_facebook:
ActionView::Template::Error: couldn't find file 'cloudinary' with type 'application/javascript'
Checked in these paths: 
  ...
    app/assets/javascripts/application.js:19
    app/views/layouts/application.html.haml:5:in `_app_views_layouts_application_html_haml__697286892514979151_70129257412400'
    test/controllers/users_controller_test.rb:984:in `test_welcome_facebook’
```

**Comment by roeeba** [comment]
Hi @zenspider. There's indeed a way of achieving that: there’s a rake task (as part of the `Rakefile` file) named `cloudinary:fetch_assets` which downloads the latest javascript libraries and CORS html and installs them into `vendor/assets`. Running `rake build` in the gem project directory will install all the necessary assets.

**Comment by zenspider** [comment]
This doesn't work for bundling github resources:

```ruby
gem "cloudinary", github:"zenspider/cloudinary_gem", branch:"my_branch"
```
