### ISSUE TITLE
Using rails_amp with cloudinary causes cl_image_tag to throw SystemStackError

### ISSUE THREAD

**Issue by wemmick** [cloudinary/cloudinary_gem#293]
I have been using Cloudinary's gem for a while with no problem, and just added the [rails_amp](https://github.com/takafumir/rails_amp) gem to give my app AMP support.  As soon as I added that gem, my app started erroring out on any page that calls cl_image_tag with ```SystemStackError (stack level too deep)```.  

My first inclination was that something was wrong with rails_amp, and [I did report it there](https://github.com/takafumir/rails_amp/issues/4), but figured I'd add it here as well because I've seen [other](https://stackoverflow.com/questions/22694091/find-cause-of-stack-level-too-deep-in-carrierwave-when-destroying-files) [reports](https://stackoverflow.com/questions/13162744/stack-level-too-deep-when-trying-to-destroy-a-child-record) of this error that appear to be Carrierwave-related with no mention of rails_amp.  

```
SystemStackError at /learning_resources/learn-american-sign-language
stack level too deep

Application Frames All Frames
unsigned_download_url
cloudinary (1.8.2) lib/cloudinary/utils.rb, line 340
cloudinary_url
cloudinary (1.8.2) lib/cloudinary/utils.rb, line 612
cloudinary_url_internal
cloudinary (1.8.2) lib/cloudinary/helper.rb, line 296
cloudinary_tag
cloudinary (1.8.2) lib/cloudinary/helper.rb, line 46
cl_image_tag
cloudinary (1.8.2) lib/cloudinary/helper.rb, line 30
image_tag_with_cloudinary
cloudinary (1.8.2) lib/cloudinary/helper.rb, line 82
image_tag
rails_amp (0.2.2) lib/rails_amp/view_helpers/image_tag_helper.rb, line 40
block in cl_image_tag
cloudinary (1.8.2) lib/cloudinary/helper.rb, line 32
cloudinary_tag
cloudinary (1.8.2) lib/cloudinary/helper.rb, line 62
cl_image_tag
cloudinary (1.8.2) lib/cloudinary/helper.rb, line 30
image_tag_with_cloudinary
cloudinary (1.8.2) lib/cloudinary/helper.rb, line 82
```

And the log (partial):

```
Rendered learning_resources/show.html.erb within layouts/application (586.8ms)
SystemStackError (stack level too deep)

SystemStackError - stack level too deep:
  app/views/learning_resources/_resource_thumbnails.html.erb:6:in `_app_views_learning_resources__resource_thumbnails_html_erb__1570303902673928730_70256559926940'
  app/views/learning_resources/show.html.erb:326:in `_app_views_learning_resources_show_html_erb___535625416886347383_70256531079900'
  lib/middleware/turbo_dev.rb:33:in `call'

    1 rows, 2 bytes
    lib/middleware/turbo_dev.rb:33:in `call'
    31 rows, 1244 bytes
    lib/middleware/turbo_dev.rb:33:in `call'
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 5]]
    1 rows, 511 bytes
    lib/middleware/turbo_dev.rb:33:in `call'
Started GET "/"
Processing by StaticPagesController#home as HTML
  GradeLevel Load (0.4ms)  SELECT "grade_levels".* FROM "grade_levels"  ORDER BY "grade_levels"."ordinal" ASC
    13 rows, 355 bytes
    app/views/static_pages/home.html.erb:28:in `_app_views_static_pages_home_html_erb___3150801494014486130_70256546922560'
    app/controllers/static_pages_controller.rb:16:in `home'
    lib/middleware/turbo_dev.rb:33:in `call'
    5 rows, 162 bytes
    app/views/static_pages/home.html.erb:28:in `_app_views_static_pages_home_html_erb___3150801494014486130_70256546922560'
    app/controllers/static_pages_controller.rb:16:in `home'
    lib/middleware/turbo_dev.rb:33:in `call'
    1 rows, 2 bytes
    app/views/static_pages/home.html.erb:28:in `_app_views_static_pages_home_html_erb___3150801494014486130_70256546922560'
    app/controllers/static_pages_controller.rb:16:in `home'
    lib/middleware/turbo_dev.rb:33:in `call'
  Rendered static_pages/home.html.erb within layouts/application (278.0ms)
SystemStackError (stack level too deep)

SystemStackError - stack level too deep:
  app/views/static_pages/home.html.erb:99:in `_app_views_static_pages_home_html_erb___3150801494014486130_70256546922560'
  app/controllers/static_pages_controller.rb:16:in `home'
  lib/middleware/turbo_dev.rb:33:in `call'
```

Hope this helps - let me know if I can provide more detail.

**Comment by roeeba** [comment]
Hi @wemmick, to better understand the issue, could you please also share the code responsible for the error?

**Comment by wemmick** [comment]
I'm not sure that I can. All I did with the rails_amp gem was install it -
I didn't change my code at all. The error I provided is all I see when I
try to load a page that has the cl_image_tag helper. Other pages work
normally.

**Comment by roeeba** [comment]
Hi @wemmick. Can you please set `enhance_image_tag: false` in your Cloudinary configuration (either in your `coudinary.yml` file or through `Cloudinary.config`)?

This will make sure that the original `ActionView::Base#image_tag` won't be replaced by Cloudinary's causing a loop of calls:

```
cl_image_tag => image_tag_without_cloudinary => image_tag => RailsAmp#image_tag => super =>cl_image_tag
```

Let me know if it helps?

**Comment by wemmick** [comment]
@roeeba It looks like that fixed it, thanks!  Is there some functionality I'm losing by not using the enhanced image tag?

**Comment by roeeba** [comment]
Hi @wemmick. The enhanced image tag is used to deliver static assets on Rails app. You can read more about it here - https://cloudinary.com/documentation/rails_image_manipulation#enhanced_image_tag.
