### ISSUE TITLE
Document cl_image_path in the README

### ISSUE THREAD

**Issue by sunnyrjuneja** [cloudinary/cloudinary_gem#295]
There's currently no reference to cl_image_path in the README. I had to comb through the lib directory to find it.

**Comment by d-mendoza** [comment]
Hi @sunnyrjuneja 
Thank you for noticing that, I have reported this to our docs team to document.

**Comment by jackieros** [comment]
Hi, cl_image_path is not in the readme as the readme only covers the basics, but it is covered in the Rails SDK documentation:
https://cloudinary.com/documentation/rails_image_manipulation#direct_url_building

Hope this is helpful.

**Comment by sunnyrjuneja** [comment]
@jackieros Didn't see it there, thanks. I only checked the Overview. I still recommend you add it to the README but feel free to close this issue if you feel otherwise.

**Comment by d-mendoza** [comment]
Closing this issue. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
