### ISSUE TITLE
Testing with Cloudinary gem

### ISSUE THREAD

**Issue by jonallured** [cloudinary/cloudinary_gem#297]
I have a Rails project that uses Cloudinary but does not currently have any feature specs. I've been working on adding this level of coverage, but I'm having trouble using capybara's `attach_file` with the `cl_image_upload_tag` helper. Any guidance for me?

I guess what I was hoping for was something like this:

https://github.com/carrierwaveuploader/carrierwave#testing-with-carrierwave

Here the CarrierWave team is giving advice about how to use their gem with testing libraries. They even include sample RSpec - anything like this for Cloudinary? Thanks!

**Comment by shirlymanor** [comment]
When using `cl_image_upload_tag` it performs client-side uploading, i.e., uploading with jQuery directly from the end-user to Cloudinary. 
You'll be able to do the spec for server-side uploads only.

**Comment by jonallured** [comment]
Bummer 😢
