### ISSUE TITLE
Gem helper methods not available for non Rails applications

### ISSUE THREAD

**Issue by thom801** [cloudinary/cloudinary_gem#301]
It appears that the helper methods like `cl_image_path` are not available unless you are using Rails. I would really like to use them in my Sinatra app. Maybe the documentation is just missing? I looked through the source and it looks like this method lives in the CouldinaryHelper class which just gets loaded in with Railties but is not easily accessible if you just import the gem in a plain ruby (Sinatra in my case) application.

**Comment by shirlymanor** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
