### ISSUE TITLE
How to upload large files?

### ISSUE THREAD

**Issue by p29892p** [cloudinary/cloudinary_gem#305]
Getting below error while uploading files to cloudinary.
CloudinaryException: File size too large.

How can i upload large files into clodinary

**Comment by jackieros** [comment]
Hi @p29892p,

You can use the `upload_large` method. 

Please have a look at [Chunked Image Upload](https://cloudinary.com/documentation/upload_images#chunked_image_upload) and [Chunked Video Upload](https://cloudinary.com/documentation/upload_videos#chunked_video_upload) in the Cloudinary documentation.

You can also see a Ruby-specific example under [Rails Video Upload](https://cloudinary.com/documentation/rails_image_and_video_upload#rails_video_upload).

Hope this helps.

**Comment by p29892p** [comment]
@jackieros

Thanks for your response. I also tried using upload_large method to upload video files which are greater than 100MB in size. But still, I'm getting this error.
