### ISSUE TITLE
Carrierwave and Cloudinary::Utils.unsigned_download_url

### ISSUE THREAD

**Issue by jgauby** [cloudinary/cloudinary_gem#310]
I have a model `Foo` with the column `image`, populated via Carrierwave. The content of the column looks like this: `image/upload/v1519387370/foo/image/1/anq2nwe1ninlndq8zdk1.jpg`

When I make `Foo.image.read`, the url generated to find the file on cloudinary is not the right one. 

Looks like this: `https://res.cloudinary.com/mybucket/image/upload/f_auto,q_auto/v1/image/upload/v1519387370/foo/image/1531409282-10-0004-2871/anq2nwe1ninlndq8zdk1.jpg`

But it should be: `https://res.cloudinary.com/mybucket/image/upload/f_auto,q_auto/v1519387370/foo/image/1531409282-10-0004-2871/anq2nwe1ninlndq8zdk1.jpg`

A buggy part `/v1/image/upload` is added L.424 (https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/utils.rb#L424).

The `use_root_path` option partially solves the problem, because there is still a `/v1` in excess.

**Comment by roeeba** [comment]
Hi @jgauby, can you please share the part of the code that generates the faulty URL so we could better understand the issue?

**Comment by jgauby** [comment]
Hi @roeeba 

That's what happens in the method `Cloudinary::Utils.unsigned_download_url` (https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/utils.rb#L353).

Consider the scoped model `Foo::Bar`:

- There is no problem with this call: `Foo::Bar.last.image.url`
```
      Foo::Bar Load (1.9ms)  SELECT  "foo_bars".* FROM "foo_bars" ORDER BY "foo_bars"."id" DESC LIMIT $1  [["LIMIT", 1]]

    From: /usr/bundle/gems/cloudinary-1.9.0/lib/cloudinary/utils.rb @ line 420 Cloudinary::Utils.unsigned_download_url:

        415:       signature = 's--' + Base64.urlsafe_encode64(Digest::SHA1.digest(to_sign + secret))[0,8] + '--'
        416:     end
        417: 
        418:     prefix = unsigned_download_url_prefix(source, cloud_name, private_cdn, cdn_subdomain, secure_cdn_subdomain, cname, secure, secure_distribution)
        419:     binding.pry
     => 420:     source = [prefix, resource_type, type, signature, transformation, version, source].reject(&:blank?).join("/")
        421:     if sign_url && auth_token && !auth_token.empty?
        422:       auth_token[:url] = URI.parse(source).path
        423:       token = Cloudinary::AuthToken.generate auth_token
        424:       source += "?#{token}"
        425:     end

    [1] pry(Cloudinary::Utils)> source
    => "foo/bar/image/1531473492-10-0001-0035/zgqzymuxowziode2ngnl.jpg"
    [2] pry(Cloudinary::Utils)> next

    From: /usr/bundle/gems/cloudinary-1.9.0/lib/cloudinary/utils.rb @ line 421 Cloudinary::Utils.unsigned_download_url:

        416:     end
        417: 
        418:     prefix = unsigned_download_url_prefix(source, cloud_name, private_cdn, cdn_subdomain, secure_cdn_subdomain, cname, secure, secure_distribution)
        419:     binding.pry
        420:     source = [prefix, resource_type, type, signature, transformation, version, source].reject(&:blank?).join("/")
     => 421:     if sign_url && auth_token && !auth_token.empty?
        422:       auth_token[:url] = URI.parse(source).path
        423:       token = Cloudinary::AuthToken.generate auth_token
        424:       source += "?#{token}"
        425:     end
        426: 

    [2] pry(Cloudinary::Utils)> source
    => https://res.cloudinary.com/mybucket/image/upload/f_auto,q_auto/v1531473496/foo/bar/image/1531473492-10-0001-0035/zgqzymuxowziode2ngnl.jpg"
```


- But with this call, the url generated to retrieve the file is bad: `Foo::Bar.last.image.file.read`

```
      Foo::Bar Load (1.4ms)  SELECT  "foo_bars".* FROM "foo_bars" ORDER BY "foo_bars"."id" DESC LIMIT $1  [["LIMIT", 1]]

    From: /usr/bundle/gems/cloudinary-1.9.0/lib/cloudinary/utils.rb @ line 420 Cloudinary::Utils.unsigned_download_url:

        415:       signature = 's--' + Base64.urlsafe_encode64(Digest::SHA1.digest(to_sign + secret))[0,8] + '--'
        416:     end
        417: 
        418:     prefix = unsigned_download_url_prefix(source, cloud_name, private_cdn, cdn_subdomain, secure_cdn_subdomain, cname, secure, secure_distribution)
        419:     binding.pry
     => 420:     source = [prefix, resource_type, type, signature, transformation, version, source].reject(&:blank?).join("/")
        421:     if sign_url && auth_token && !auth_token.empty?
        422:       auth_token[:url] = URI.parse(source).path
        423:       token = Cloudinary::AuthToken.generate auth_token
        424:       source += "?#{token}"
        425:     end

    [1] pry(Cloudinary::Utils)> source
    => "image/upload/v1531473496/foo/bar/image/1531473492-10-0001-0035/zgqzymuxowziode2ngnl.jpg"
    [2] pry(Cloudinary::Utils)> next

    From: /usr/bundle/gems/cloudinary-1.9.0/lib/cloudinary/utils.rb @ line 421 Cloudinary::Utils.unsigned_download_url:

        416:     end
        417: 
        418:     prefix = unsigned_download_url_prefix(source, cloud_name, private_cdn, cdn_subdomain, secure_cdn_subdomain, cname, secure, secure_distribution)
        419:     binding.pry
        420:     source = [prefix, resource_type, type, signature, transformation, version, source].reject(&:blank?).join("/")
     => 421:     if sign_url && auth_token && !auth_token.empty?
        422:       auth_token[:url] = URI.parse(source).path
        423:       token = Cloudinary::AuthToken.generate auth_token
        424:       source += "?#{token}"
        425:     end
        426: 

    [2] pry(Cloudinary::Utils)> source
    => "https://res.cloudinary.com/mybucket/image/upload/f_auto,q_auto/v1/image/upload/v1531473496/foo/bar/image/1531473492-10-0001-0035/zgqzymuxowziode2ngnl.jpg"
```

There is a buggy part in the url: `...v1/image/upload/v1531473496/foo/bar/image...`

**Comment by taragano** [comment]
A possible reason for that could be due to a problematic DB assignment. Could you please share the output of the following for the mentioned model record?

    Foo.image.my_public_id
Specifically, I see some inconsistencies between the value of `...foo/image/1/anq2nwe1ninlndq8zdk1.jpg` that's assigned in the column vs `...foo/image/1531409282-10-0004-2871/anq2nwe1ninlndq8zdk1.jpg` that's generated afterwards (note the `/1/` vs `/1531409282-10-0004-2871/` parts).

Also, we believe it'd be easier to take a deeper look with the actual public IDs and the real cloud_name. It'd be great if you could share those with us. If privacy is an issue, please feel free to open a [support ticket](https://support.cloudinary.com/hc/en-us/requests/new) and we'll be happy to continue this there.

**Comment by jgauby** [comment]
`Foo::Bar.image.my_public_id` => `foo/bar/image/575/ognlmdk4odbhmzgyn2ex`

I have overrided the method `public_id` in my model. The problem would come from there?

```
  def public_id
    id = model.id.presence || cache_id
    "#{model.class.to_s.underscore}/#{mounted_as}/#{id}/#{Base64.encode64(Digest::SHA1.hexdigest(Cloudinary.config.salt_public_id.to_s + id.to_s)).downcase.gsub(/[^a-z0-9]/, "").sub(/^[0-9]+/, '')[0,20]}"
  end
```

**Comment by jgauby** [comment]
Hello,

The problem was solved with the help of the support. The images were removed, but the 30-day cloudinary CDN cache kept them alive, so our code behavior was very unpredictable!
