### ISSUE TITLE
Old image kept on cloudinary

### ISSUE THREAD

**Issue by Nkadze** [cloudinary/cloudinary_gem#311]
Hi,
When I'm updating image from rails form, through `update_attributes` and carrierwave uploader, on cloudinary both: new and old images are kept. Is it possible to override this behavior? 
Thanks in advance.

**Comment by idobarnoam** [comment]
Hi @Nkadze 

Could you maybe share a code snippet so we could verify we are on the same page?

Also if you could share the versions that are being used of your Ruby, Rails, Cloudinary GEM and CarrierWave installations we could take a closer look.

**Comment by Nkadze** [comment]
@idobarnoam, Thanks for quick response,

Those are package versions:
```
ruby '2.3.1'
'rails', '~> 5.1.5'
cloudinary (1.9.1)
carrierwave (1.2.3)
```
Uploader:
``` ruby
class ImageUploader < CarrierWave::Uploader::Base
  include Cloudinary::CarrierWave

  process resize_to_fit: [1920, 1080]

  version :small do
    cloudinary_transformation \
    gravity:      'auto',
    width:        150,
    height:       100,
    crop:         'fill',
    quality:      'auto',
    fetch_format: :auto
  end

end
```
Model:
``` ruby
mount_uploader :featured_image, ImageUploader
```
Update Code:

``` ruby
obj.update_attributes(remote_featured_image_url: url)
```
or:
``` ruby
@model.update(model_params)
#--------------
def model_params
   params.require(:model).permit(:name, :featured_image, :featured_image_cache)
end
```

**Comment by taragano** [comment]
Thank you @Nkadze. We're taking a look and we'll let you know of any insights.

**Comment by toyflish** [comment]
I have the same problem, updating an attachment through a fileupload creates a new file on cloudinary leaving the old one untouched. If I look at the carrier_wave.rb file, there is only a Cloudinary::Uploader.destroy call in the delete method, but no after_update functionality to destroy the old public_id.

**Comment by roeeba** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
