### ISSUE TITLE
Support sassc?

### ISSUE THREAD

**Issue by mattbrictson** [cloudinary/cloudinary_gem#316]
I tried using the cloudinary gem together with sassc-rails and it looks like this combination is not currently supported.

The cloudinary gem expects `sass-rails` to be present in the Gemfile, so I applied [this workaround](https://github.com/sass/sassc-rails/issues/6#issuecomment-228782138):

```
# Gemfile
gem 'sass-rails', require: false
gem 'sassc-rails',
```

This allows Rails to boot, but then when I attempt to use the `cloudinary_url` function in one of my `.scss` files I get the following error:

```
SassC::SyntaxError
Error: Function cloudinary_url doesn't support keyword arguments
```

Do you have any suggestions for using `sassc-rails` together with `cloudinary`? The sassc gem is 4x faster than Ruby sass and is a must-have for larger projects. Ideally the cloudinary gem would support either sass or sassc out of the box, without workarounds or patches.

**Comment by shirlymanor** [comment]
I'm sorry for the late response!
It's on our road-map but no ETA yet.
We will update here when will have any insights.

**Comment by benkubic** [comment]
Any update on this? Rails 6 is coming soon and it will require `sassc-rails` by default, so the gem is blocking our upgrade path

**Comment by nicovak** [comment]
PR linked, I hope It will be fixed soon, `rails 6` isn't fully compatible yet.

**Comment by GeoffTidey** [comment]
Looks like this is stopping our migration to rails 6 

```
SassC::SyntaxError at /en
Error: Function cloudinary-url doesn't support keyword arguments
        on line 30:25 of app/assets/stylesheets/sharing.scss
        from line 27:9 of app/assets/stylesheets/application.scss
>>       background-image: cloudinary-url('icons/share-facebook.svg', $quality:
   ------------------------^
```

Any news on an ETA for a fix?

**Comment by shirlymanor** [comment]
We are actively working on a new version that will handle Rails6 sassc. The current ETA is the end of this month.
