### ISSUE TITLE
rest-client error / KeyError Exception: key not found: :ciphers 

### ISSUE THREAD

**Issue by gabriel-dehan** [cloudinary/cloudinary_gem#320]
Hello,

Quite a few of us (I am part of a ruby bootcamp and a good number of students/teachers) have been having an error when trying to upload files to cloudinary: `KeyError Exception: key not found: :ciphers`. 
It is clearly coming from the fact that the gem is using a version of `rest-client` inferior to 2.0 and the only way of fixing it is either to downgrade the cloudinary gem so it starts using a `rest-client` version superior to 2.0 or force the `rest-client` version to be `>= 2.0.x`

This never happened before and started happening a few days ago, probably with the release of your 1.10.0 

The thing is it doesn't seem to be concerning everybody, only a good amount of us so that's kind of awkward. 
Finding a clean fix (not having to downgrade your gem or force the rest-client's version) would be amazing.

Cheers

**Comment by rwehresmann** [comment]
Same issue here.

**Comment by roeeba** [comment]
Hey guys, please see updates on https://github.com/cloudinary/cloudinary_gem/issues/322.
