### ISSUE TITLE
1.10.0 use old version of rest-client

### ISSUE THREAD

**Issue by dsennerlov** [cloudinary/cloudinary_gem#322]
Upgrading to 1.10.0 give me an old version of rest-client (1.8.0):
![image](https://user-images.githubusercontent.com/1035255/48408375-7791dc00-e739-11e8-8a91-cf47750e8c75.png)

Downgrading to 1.9.1 however:
![image](https://user-images.githubusercontent.com/1035255/48408402-8a0c1580-e739-11e8-93c9-38752fc7e1d0.png)

Only difference to 1.9.1 is this:
![image](https://user-images.githubusercontent.com/1035255/48408643-17e80080-e73a-11e8-94ca-8a6ad4c6ad81.png)

Uninstalling rest-client 1.8.0:
![image](https://user-images.githubusercontent.com/1035255/48408965-e885c380-e73a-11e8-9e26-d550b23feda9.png)

Ruby version: 2.5.1
![image](https://user-images.githubusercontent.com/1035255/48409084-38fd2100-e73b-11e8-92df-3d601144dbff.png)

**Comment by dsennerlov** [comment]
Operationally, this is not a big problem right now, as I can fix the Cloudinary gem to 1.9.1, but long term this will be unsustainable.

**Comment by dsennerlov** [comment]
Related issue: https://github.com/cloudinary/cloudinary_gem/issues/320

**Comment by msdundar** [comment]
This version of the `rest-client` have several vulnerabilities:

https://app.snyk.io/vuln/SNYK-RUBY-RESTCLIENT-20211
https://app.snyk.io/vuln/SNYK-RUBY-RESTCLIENT-20204

Therefore, it must be upgraded as soon as possible.

**Comment by roeeba** [comment]
Hi @msdundar. Thank you for pointing it out. I've opened a ticket with our dev team. Update to follow.

**Comment by tocker** [comment]
Hi All!

Thanks for the heads-up!

Our gemspec specifies the dependency on rest-client conditionally based on the ruby version. Specifically, rest-client > 2.0 depends on ruby > 2.0.

https://github.com/cloudinary/cloudinary_gem/blob/1521391431608734d345a9bba3af96efc5b4e639/cloudinary.gemspec#L28-L46

Our gemspec hasn't changed in _two years_. But it looks like something changed in the way rubygems processes the gemspec - or in our build environment.

We'll look into it!

PS we'll drop support for ruby 1.9 and older in the next major release - this will make things much simpler!

**Comment by Jesterovskiy** [comment]
@tocker with `ruby 2.5.1p57`, after update, I get: json (2.1.0) -> json (1.8.6), rest-client (2.0.2) -> rest-client (1.8.0), mime-types (3.2.2) -> mime-types (2.99.3)

**Comment by rendekarf** [comment]
@Jesterovskiy @tocker I'm using rbenv with ruby version ```2.5.3```. Not sure why but when I run ```bundle install``` with cloudinary included in my Gemfile (no version specified) I end up with the ```RUBY_VERSION >= "1.9"``` block executing which forces me to install ```rest-client@1.6.7``` - the vulnerable version.

I can confirm that cloudinary is at version ```1.10.0``` in my Gemfile.lock.

I've tried removing rbenv completely and reinstalling 2.5.3. Same result. Any idea?

**Comment by rendekarf** [comment]
As @dsennerlov pointed out, I temporarily fixed the issue by fixing cloudinary to version ```1.9.1```

**Comment by tocker** [comment]
Hi @dsennerlov, @msdundar , @Jesterovskiy, @rendekarf,

I published a release candidate with fixed dependencies. I'd appreciate it if you gave it a test drive:

```
# Gemfile
gem "cloudinary", "1.10.1.pre.rc"
```

Thanks!

**Comment by Jesterovskiy** [comment]
@tocker Everything fine, thank you!

**Comment by shirlymanor** [comment]
Thank you for the update!

**Comment by msdundar** [comment]
When are you going to publish a new release? `rest-client` is still vulnerable and needs to be upgraded.

**Comment by roeeba** [comment]
Hi @msdundar. The issue is fixed in 1.11.0.
