### ISSUE TITLE
Image cloudinary transformation not working as it should be

### ISSUE THREAD

**Issue by kashiftufail** [cloudinary/cloudinary_gem#323]
Hi,

   I'm using cloudinary gem for saving images using carrierwave. Here is my uploader code below

        class AvatarUploader < CarrierWave::Uploader::Base
          include Cloudinary::CarrierWave
          version :simple do
            process :resize_to_fill => [633, 400, :fill]
            process :convert => 'jpg'
            cloudinary_transformation :quality => 10
          end
        end

But image is saving with its actual size. cloudinary_transformation "quality" not working.Image actual size was 432kb and after saving it is 428kb.

Also overlay text is not working with cl_image_tag as i list below

       <%=cl_image_tag("https://res.cloudinary.com/adstous/image/upload/v1542166219/sample.jpg", 
               :transformation=>[
                   {:width=>400, :crop=>"scale"},
                   {:overlay=>{:font_family=>"arial", :font_size=>60, :text=>"Sea%20Shell"}, :gravity=>"north", 
                   :y=>20}])
       %>

I believe this is also not working quality=>"auto:low" with cl_image_tag.

My Ruby is 2.5.0 and Rails is 5.2.1 and cloudinary is on 1.10.0

Please help.

**Comment by taragano** [comment]
1. Regarding the line of:

    ```ruby
    process :resize_to_fill => [633, 400, :fill]
    ```
    The third argument is expected to be a `gravity` value, while `fill` is a `crop` value. You can one of the `gravity` values, e.g., `north` (default is `center`).

2. The current code will not process the uploaded image, it'll create the transformation as a derived image on delivery. In other words, it'll upload the original as is, and then you'll be able to access a derived version by accessing it with something like: 

    ```ruby
    <%= image_tag(mymodel.image.simple.url, :class => "thumbnail inline") %>
    ```
3. In order to process the original image, i.e., transform before storing it in your account, you can use the code outside a `version`, e.g.,:
    ```ruby
    class AvatarUploader < CarrierWave::Uploader::Base
        include Cloudinary::CarrierWave

        process :convert => "jpg"
        process :resize_to_fill => [633, 400]
        cloudinary_transformation :quality => 10
        ...
    end
    ```

4. Regarding the question about the overlay - For resources of any other type than `upload`, the `type` needs to be explicitly set, e.g.,:

    ```ruby
    cl_image_tag("https://res.cloudinary.com/adstous/image/upload/v1542166219/sample.jpg", :type=>"fetch", :transformation=>[ {:width=>400, :crop=>"scale"}, {:overlay=>{:font_family=>"arial", :font_size=>60, :text=>"Sea%20Shell"}, :gravity=>"north", :y=>20} ])
    ```
    Alternatively, you can use:

    ```ruby
    fetch_image_tag("https://res.cloudinary.com/adstous/image/upload/v1542166219/sample.jpg", :transformation=>[ {:width=>400, :crop=>"scale"}, {:overlay=>{:font_family=>"arial", :font_size=>60, :text=>"Sea%20Shell"}, :gravity=>"north", :y=>20} ])
    ```

**Comment by kashiftufail** [comment]
Thanks working.

cloudinary_transformation :transformation => [
      {:width => 633, :height => 400, :crop => :limit},
      {:overlay=>{:font_family=>"Lobster", :font_size=>30,:color => "#8b0f02",:opacity => 90, :text=>"adstous"}},
       {:quality => 50}
    ]
In above code just need to chnage text color. But color attribute not working, always text color of "adstous" is black on saving.

Help please....

**Comment by roeeba** [comment]
Hi @kashiftufail. The `color` and `opacity` parameters needs to be set outside the overlay object, like this:

```
cloudinary_transformation :transformation => [
{:width => 633, :height => 400, :crop => :limit},
{:overlay=>{:font_family=>"Lobster", :font_size=>30, :text=>"adstous"}, :color => "#8b0f02", :opacity => 90},
{:quality => 50}
]
```
