### ISSUE TITLE
Orignal file download doesnt work when Strict transformations are on

### ISSUE THREAD

**Issue by MichalRemis** [cloudinary/cloudinary_gem#328]
When Cloudinary Strict transformations are turned on and in Rails console I try to download original of previously uploaded file e.g. `Cloudinary::Downloader.download('FQPPXFKhDjx1d9LZaMtpuQac')`, it doesnt work and returns only empty string '', yet it works fine if Strict transformations are off. 

This causes really ugly bug with Rails Active Storage, because when file is uploaded, Rails tries to analyze it via MiniMagick and DelayedJob, but it fails to download original file and fails again and again, slowly depleting Cloudinary quota.

**Comment by brian-cloudinary** [comment]
Hi @MichalRemis,

When using Cloudinary's download function, it creates a Cloudinary URL based on the public id of the image (in the case of `FQPPXFKhDjx1d9LZaMtpuQac`, the resulting URL will be `http://res.cloudinary.com/<CLOUD-NAME>/image/upload/FQPPXFKhDjx1d9LZaMtpuQac`), and performs a `GET` request to receive the image. 

Note that the generated URL does not have an extension. When a Cloudinary URL omits the file extension, it is categorized as a `no extension` transformation. When Strict transformations are enabled, it only possible to retrieve the original image by specifying the format in which it was uploaded at the end of the public id (ie. `FQPPXFKhDjx1d9LZaMtpuQac.jpg`), signing the URL via the `sign_url` parameter, or allowing the `no extension` transformation under the transformations tab in your Cloudinary console.

**Comment by MichalRemis** [comment]
Thank you for response Brian. Enabling `no extension` transformation in Cloudinary console helped (for those, who cant find it in list , click _more transformations.._ to show all of them).

It's problem with _activestorage-cloudinary-service_ gem then, because it downloads image for AnalyzeJob without signing it and therefore it doesn't work with strict transformations. I will open issue there.
