### ISSUE TITLE
How i can repeat overlay text multitime on same photo

### ISSUE THREAD

**Issue by kashiftufail** [cloudinary/cloudinary_gem#332]
Hi,

   I have this code in my carrierwave uploader

      cloudinary_transformation :transformation => [
            {:width => 495, :height => 420, :crop => :limit},
            {:opacity => 40, :color => "rgb:1D292F", :overlay=>{:font_family=>"Vollkorn",:font_size=>15, 
            :text=>"test text"}},
            {:quality => 90}
       ]

I want "test text" repeat on photo multiple times on different positions. 
Is it possible?

**Comment by igy** [comment]
Hi Kashif,

Yes, you can do that by adding another transformation which adds the second piece of text.

Using your example, you can do something like this:

 cloudinary_transformation :transformation => [
      {:width => 495, :height => 420, :crop => :limit},
      {:opacity => 40, :color => "rgb:1D292F", :overlay=>{:font_family=>"Vollkorn",:font_size=>15, :text=>"test text"}},
      {:opacity => 40, :color => "rgb:1D292F", :overlay=>{:font_family=>"Vollkorn",:font_size=>15, :text=>"test text", gravity:"north"}},
      {:quality => 90}
    ]        
 
This should add the same text a second time, near the top of the image.
Could you please try and let me know if it works for you?

**Comment by kashiftufail** [comment]
Its not working. Only display text one time as it was displaying before.
There should be a way to print text multiple times on photo using x,y
positions.
Thanks

**Comment by igy** [comment]
Hi Kashif, did that example work for you? If not, please let us know.

**Comment by kashiftufail** [comment]
Thanks,

It works for me.

**Comment by jackieros** [comment]
@kashiftufail - Just wanted to add that if you are using the identical text multiple times, you might also want to take advantage of the option to define the text string as a user-defined variable, and then specify the variable as the value for each of the text overlays
https://cloudinary.com/documentation/user_defined_variables#text_overlays

This would also enable you to define your multiple-text-overlay transformation as a named transformation and pass different text to it in each case via the variable.

Hope that's helpful as well.
