### ISSUE TITLE
Cloudinary not compatible with carrierwave 2.0

### ISSUE THREAD

**Issue by dansteele** [cloudinary/cloudinary_gem#344]
https://github.com/carrierwaveuploader/carrierwave/blob/master/CHANGELOG.md

Getting 
```
NotImplementedError:
  Need to implement #cache! if you want to use Cloudinary::CarrierWave::Storage as a cache storage.
```

Need to implement `cache!` 👇 
https://github.com/carrierwaveuploader/carrierwave/blob/f15f4ba71dd2c78e8df494bf65938bbaf13960f9/lib/carrierwave/storage/abstract.rb#L26

**Comment by ryansch** [comment]
If you don't need a consistent cache across servers, use: `config.cache_storage = :file`

**Comment by aleksandar-cloudinary** [comment]
Hi @dansteele. Thanks for reporting this. I'm checking this internally and will update this thread with more details.

**Comment by dansteele** [comment]
@aleksandar-cloudinary Any news on this?

**Comment by jaicab** [comment]
Any news on this? Would be great to see. 👏

**Comment by roeeba** [comment]
Hi @jaicab. Sorry, no updates at this point. It's currently not on our immediate plans, but we'll definitely update if there'll be any progress. Thank you for your patience.

**Comment by ryansch** [comment]
To clarify: if you don't attempt to use the cloudinary storage as cache storage then it works like it did with 1.x.  Carrierwave 2.0 changed the default cache storage to be the same as the regular storage.

**Comment by cstratulat** [comment]
Having a somewhat similar issue here. I'm getting `NotImplementedError: Need to implement #delete_dir! if you want to use Cloudinary::CarrierWave::Storage as a cache storage.`

 My `carrierwave.rb` initializer is:

```
if Rails.env.test? or Rails.env.cucumber?
  CarrierWave.configure do |config|
    config.storage = :file
    config.cache_store = :file
    config.enable_processing = false
  end
end
```

I didn't change anything else when upgrading to `carrierwave 2.0.2`. For now, I think I'll have to stick to a pre 2.0 version, which is a bummer.

**Comment by roeeba** [comment]
@cstratulat Cloudinary is not currently intended for cache storage. as @ryansch mentioned, to overcome this limitation, you will have to configure the cache storage explicitly.

**Comment by ryanwaldorf** [comment]
To fix this issue you need to explicitly initialize cache storage to file for BOTH CarrierWave and Cloudinary.  Setting it to file for Cloudinary alone will not work.  

So for others seeing this add a CarrierWave configuration file with this code:
`
CarrierWave.configure do |config|
  config.cache_storage = :file
end
`
If you then add config.cache_storage to your Cloudinary initializer you can get this working.
