### ISSUE TITLE
Rails 6 deprecation warning

### ISSUE THREAD

**Issue by maymillerricci** [cloudinary/cloudinary_gem#351]
On Rails 6, I am getting a deprecation warning which I have narrowed down to be coming from this gem:

```
DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ActionText::ContentHelper, for example,
the expected changes won't be reflected in that stale Module object.

These autoloaded constants have been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from <top (required)> at /Users/may/Desktop/repos/brain-possible/config/environment.rb:5)
```

Some more information [here](https://github.com/rails/rails/issues/36363) and [here](https://github.com/rails/rails/issues/36546).

**Comment by aleksandar-cloudinary** [comment]
Hi, @maymillerricci. Thanks for raising this, we'll take a look and provide some more details on that shortly.

**Comment by TImPDaley** [comment]
Yes I have the same issue ... Cloudinary linkage causing deprecation warning when I run rspec:
DEPRECATION WARNING: Initialization autoloaded the constants ActionText::ContentHelper and ActionText::TagHelper.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ActionText::ContentHelper, for example,
the expected changes won't be reflected in that stale Module object.

`config.autoloader` is set to `classic`. These autoloaded constants would have been unloaded if `config.autoloader` had been set to `:zeitwerk`.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from <top (required)> at /home/ubuntu/environment/iem-fellowship/config/environment.rb:5)

**Comment by rajdeep7Singh** [comment]
Any update on this? Facing the same issue.

**Comment by dylangrafmyre** [comment]
Still having this issue. Any updates on https://github.com/cloudinary/cloudinary_gem/pull/382?
