### ISSUE TITLE
Recommended approach for form re-render after validation error

### ISSUE THREAD

**Issue by yourtallness** [cloudinary/cloudinary_gem#362]
Carrierwave recommends including a `_cache` hidden input (e.g. `image_cache`) so that a reference to the cached file can be maintained if the form needs to be reloaded because of errors.

The problem is that since the file is never actually uploaded to Cloudinary (which is OK), it's not that easy to render a thumbnail of the already uploaded file so that the end user can see they have already selected a file and need not provide it again.

A silly solution I could think of is creating the thumbnail manually with rmagick and render that, but this approach introduces an additional dependency.

What is the preferred way of handling this with the cloudinary carrierwave integration?

TIA

**Comment by aleksandar-cloudinary** [comment]
@yourtallness Hi. Do you have image_cache set in the attr_accessible declaration within your model or permitted params in Rails 4+? Then may be able to use;

```
<%= f.hidden_field :image_cache %>
<%= image_tag(@foo.image_url) if @foo.image_cache? %>
```

Also, if you look into the Cache directory, is there already a cached thumbnail (thumb) version even if the form validation fails?

**Comment by yourtallness** [comment]
@aleksandar-cloudinary The originally uploaded image will be in the cache.

Thing is, since it has not been uploaded to Cloudinary, transformations are not available for rendering it as an existing file thumbnail.

**Comment by aleksandar-cloudinary** [comment]
@yourtallness Yes, the transformations won't be available. I've seen some cases where the CarrierWave gem also has a thumbnail version in the cache in addition to the original image, is that not the case in your setup? If so, one way to work around this can be to use MiniMagick (will involve an additional dependency as you mentioned) to create the thumbnail or load the original from cache but resize within your template directly.

**Comment by aleksandar-cloudinary** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
