### ISSUE TITLE
Serve static images referenced in scss

### ISSUE THREAD

**Issue by 1dolinski** [cloudinary/cloudinary_gem#364]
I followed the below blog post to allow cloudinary to serve my static images. It works great!...  Except for images referenced in my scss files which are still referencing the asset pipeline, Is this supported?

https://cloudinary.com/blog/how_to_deliver_your_static_images_through_a_cdn_in_ruby_on_rails

**Comment by aleksandar-cloudinary** [comment]
Hi @1dolinski I'm checking this with our team and will provide some more details shortly.

**Comment by 1dolinski** [comment]
@aleksandar-cloudinary Great -- thank you!

**Comment by aleksandar-cloudinary** [comment]
@1dolinski Is your project using Rails 6? We do have a pull request open to support Rails 6 sass which you can find here: https://github.com/cloudinary/cloudinary_gem/pull/346. Once that's released it should also allow you to reference your images from scss. Also, just double-checking that your config has the relevant settings set and also you've run the rake tasks for the scss referenced files?
