### ISSUE TITLE
Unable to upload docx

### ISSUE THREAD

**Issue by mikefogg** [cloudinary/cloudinary_gem#365]
Hey there!

I've been working on uploading a `.docx` file using the new ActiveStorage setup and getting the following error:

`ActiveStorage::IntegrityError (Unsupported ZIP file)`

Doing a bit of research, it looks like in `ActiveStorage::Service::CloudinaryService` it's firing off the `upload` method correctly.

Logging out `resource_type(io, key)` (https://github.com/cloudinary/cloudinary_gem/blob/master/lib/active_storage/service/cloudinary_service.rb#L36) we're getting `image`.

Inside `resource_type` we're saying `return image if key doesn't respond to :attributes` and in this case key is just a long string, so that's returning the default image. Updating that line (https://github.com/cloudinary/cloudinary_gem/blob/master/lib/active_storage/service/cloudinary_service.rb#L168) to `return 'raw'` works fine :) But of course, that's not a good solution.

Wanted to make sure I wasn't doing something wrong before I did much else! I uploaded a sample docx that I'm unable to upload.

[Project proposal.docx](https://github.com/cloudinary/cloudinary_gem/files/3783260/Project.proposal.docx)

**Comment by const-cloudinary** [comment]
@mikefogg thanks for reporting this bug, we are working on it!
