### ISSUE TITLE
API Feature: retrieving images by creation date

### ISSUE THREAD

**Issue by assembler** [cloudinary/cloudinary_gem#37]
It would be great to have the ability to programmatically tag and untag images.

Users can upload as much images as they want using cloudinary javascript plugin. These images may never be used by the actual application (user can change his mind in the process). 

Use case:

* user uploads image using javascript -> image is automatically tagged with `tmp` tag (already supported)
* when user submits the form, server processes all the images and through the `admin_api` it removes `tmp` tag from them
* cron job contacts cloudinary to remove all images tagged with `tmp` that are *older than 1 day*

It would also require the ability to filter images based on creation date through api..

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
