### ISSUE TITLE
render a problem, my gem is 1.5.2

### ISSUE THREAD

**Issue by Woner1** [cloudinary/cloudinary_gem#376]
Why does this happen?
![image](https://user-images.githubusercontent.com/24207130/70505971-46feba80-1b64-11ea-86b5-c02744d4cbb0.png)

**Comment by aleksandar-cloudinary** [comment]
Hi @Woner1 At which stage/action does this error happen and what is the minimal amount of code required to reproduce? In addition, could you please upgrade to the latest gem and let us know if that works?

**Comment by Woner1** [comment]
Now, I update gem version to 1.13.1, but problem is the same. Image can be uploaded to cloudinary, but result render error. This exception was thrown by gem cloudinary, which confused me.
![image](https://user-images.githubusercontent.com/24207130/70522594-5f7acf00-1b7c-11ea-8076-110c178672bd.png)

**Comment by aleksandar-cloudinary** [comment]
@Woner1 What is the content of `result` if you just print it rather than render as JSON?

**Comment by Woner1** [comment]
> @Woner1 What is the content of `result` if you just print it rather than render as JSON?

the result is 
`
"undefined method `http_code' for #<NoMethodError: undefined method `code' for nil:NilClass>"
`

**Comment by aleksandar-cloudinary** [comment]
@Woner1 Thanks! Could you please share an example image that you tried to upload that produces this error and your cloud name? I'll then check the logs on our side. In addition, does that happen for every upload? Did it work previously but stopped recently?

**Comment by Woner1** [comment]
Thanks!  I have other website, I have several websites that use cloudinary to upload, but one of them will have this problem, other website can be uploaded normally

Here is my upload picture url `https://res.cloudinary.com/cslrstag/image/upload/v1576052462/knight/customer_review/kopnztcgfkt2auorecjq.png`

Here is my cloudinary account
`developers@castlery.com`

Her is my upload image floder
`knight/customer_review`

**Comment by Woner1** [comment]
> @Woner1 Thanks! Could you please share an example image that you tried to upload that produces this error and your cloud name? I'll then check the logs on our side. In addition, does that happen for every upload? Did it work previously but stopped recently?

@aleksandar-cloudinary  Excuse me, do you find anything in the log?

**Comment by aleksandar-cloudinary** [comment]
@Woner1 Apologies for the slight delay. Looking at the logs the uploads aren't producing any errors and are working as you mentioned too. Are you using CarrierWave in the example when you can reproduce this? Is this also reproducible using the sample app (https://github.com/cloudinary/cloudinary_gem/tree/master/samples/basic) that is included in this Gem? I'm wondering what the minimum amount of code/dependencies needed to reproduce this is so we can rule out all other variables. Lastly, what is the content of `image` and could you try using just: `result = Cloudinary::Uploader.upload(image)`, does that produce the same result?

**Comment by Woner1** [comment]
> @Woner1 Apologies for the slight delay. Looking at the logs the uploads aren't producing any errors and are working as you mentioned too. Are you using CarrierWave in the example when you can reproduce this? Is this also reproducible using the sample app (https://github.com/cloudinary/cloudinary_gem/tree/master/samples/basic) that is included in this Gem? I'm wondering what the minimum amount of code/dependencies needed to reproduce this is so we can rule out all other variables. Lastly, what is the content of `image` and could you try using just: `result = Cloudinary::Uploader.upload(image)`, does that produce the same result?

The log

**Comment by Woner1** [comment]
@aleksandar-cloudinary Use `result = Cloudinary :: Uploader.upload（image)` , upload successful, I didn't add CarrierWave gem, I try to add gem CarrierWave. But the problem is not solved.  does that produce the same result? error is also `"undefined method `http_code' for #<NoMethodError: undefined method `code' for nil:NilClass>"`

**Comment by aleksandar-cloudinary** [comment]
@Woner1 There isn't a way to check the exact response sent back. When you mentioned that using `result = Cloudinary:: Uploader.upload（image)` works, do you mean the image uploads and also you do not see the exception?

Since you are able to replicate this, what you can do is edit the gem code, specifically (https://github.com/cloudinary/cloudinary_gem/blob/b48338208891abafdfbd02a28b2be44e7e964b12/lib/cloudinary/uploader.rb#L340) and add a single line of code to print the `result` object that is returned. And then perform an upload as you would normally that would print the output of the response and the error. Then we'll be able to see the content of the response.
