### ISSUE TITLE
Disable timeout for RestClient

### ISSUE THREAD

**Issue by pk121** [cloudinary/cloudinary_gem#384]
While using the gem, we can pass `timeout` in `options` which is further used while making request using `RestClient`.

Example: https://github.com/cloudinary/cloudinary_gem/blob/d84227247d6ff1f9cee1a069ddc892e548854798/lib/cloudinary/uploader.rb#L320

To disable timeouts, a value of `-1` or `nil` must be provided as timeout to RestClient.
`-1` has been deprecated by RestClient and instead it is advised to use `nil` to disable timeout.
https://github.com/rest-client/rest-client/blob/2c72a2e77e2e87d25ff38feba0cf048d51bd5eca/lib/restclient/request.rb#L708

If we use `nil` from client side, Cloudinary gem will use the default of 60 seconds.
Please add support for disabling timeouts for API calls.
The processing time of rename API call is dependent upon number of transformations and usually exceeds the default timeout of 60 seconds.

The `nil` timeout should be supported via both `options` param in API calls as well as through `Cloudinary.config.timeout`

**Comment by taragano** [comment]
Hi @pk121,
Can you share your use case that requires an unlimited timeout from your Ruby server side?
Note that there's also an enforced timeout from the Cloudinary server end.

**Comment by pk121** [comment]
Hi @taragano,
We're using the rename API to rename public IDs of some images. The API call usually takes more than 60 seconds to process and consequently times out with the default timeout of 60 seconds.
Since all exceptions from the gem are embedded in `CloudinaryException`, there's no way to identify on server side if the exception is due to timeout or some other issue, and hence can't be handled properly. If the exception is due to timeout, the rename operation is already in process but if the exception is due to other issue, it might be a different issue that need to le looked up/retried.

Since rename API takes time proportional to number of transformations associated with the image, there's no viable way to predict the ideal timeout and hence an option to disable timeout seems ideal.

We want exceptions to be there only when the specific operation has failed. With timeouts, the operations are already in process but not finished, while the exception is thrown.

**Comment by pk121** [comment]
@taragano 
We're already using the API with timeouts disabled (using `timeout: -1`) but since value of `-1` is deprecated it's not recommended for use and the deprecation warnings pollute our logs.
This request is not absolutely important for us, but something Cloudinary devs might want to look into.

**Comment by roeeba** [comment]
Hi @pk121 . Thanks for sharing the use-case. I'm going to open an internal ticket to our engineers. We will update here on any progress done.
