### ISSUE TITLE
uninitialized constant Cloudinary::CarrierWave::Utils after upgrading from 1.11.1 to 1.14

### ISSUE THREAD

**Issue by yourtallness** [cloudinary/cloudinary_gem#399]
## Issue description

Upgraded our stack from rails 4.2 + ruby 2.4 to rails 5.2 + ruby 2.5.
Carrierwave was upgraded to 2.10 from 1.3.1
Cloudinary up to 1.14 from 1.11.1.

Now the `remote_image_url` helper is no longer working.
Since this is not an issue reported already, I assume we must be something wrong.

We are getting:

`NameError (uninitialized constant Cloudinary::CarrierWave::Utils)`

 when trying to set a `remote_image_url` on a model with a mounted uploader.

## Our base uploader

```
class BaseUploader < CarrierWave::Uploader::Base
  include Cloudinary::CarrierWave

  # stuff

end
```

## Debugging info

Setting a breakpoint here:

`/Users/mark/.rvm/gems/ruby-2.5.8/gems/cloudinary-1.14.0/lib/cloudinary/carrier_wave/remote.rb:7`

has shown that the `Utils` module is being resolved under the `Cloudinary::CarrierWave` namespace whereas its actual namespace is `Cloudinary::Utils`.

## Operating System
Mac

## Environment and Libraries
Cloudinary Ruby SDK version - 1.14
Ruby Version - 2.5.8
Rails Version - 5.2.4.3
Other Libraries (Carrierwave) - 2.1.0

Please advise.

**Comment by aleksandar-cloudinary** [comment]
Hi @yourtallness. Thanks for submitting this. We've found the change that introduced this and we'll add a ticket on our side for the fix and relevant test cases to cover this flow. I'll share more details on the progress and as soon as it's ready for release.

**Comment by yourtallness** [comment]
Thank you @aleksandar-cloudinary 

Do you have a rough ETA on this?

**Comment by aleksandar-cloudinary** [comment]
I'm working on the changes currently and should have more details in a few days. Once the change is ready I will follow up with our SDK team as to when we can next bundle this (and any other changes) in a release.
