### ISSUE TITLE
Version '1.16.0' Safari error "Invalid regular expression: invalid group specifier name"

### ISSUE THREAD

**Issue by deberle** [cloudinary/cloudinary_gem#410]
## Bug report for Cloudinary Ruby SDK
The error came up with version 1.16.0

## Describe the bug in a sentence or two.
On Safari we get a javascript error that prevents image loading. 

The error is:
"Invalid regular expression: invalid group specifier name"

it crashes in `Expression.normalize`, apparently Safari cannot parse the new Regex. 

Check for example: 
https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

I believe the problem is around here: https://github.com/cloudinary/cloudinary_gem/commit/5149963ef99e11a32eba72e3193058eb6523ec00

## Issue Type (Can be multiple)
[ ] Build - Can’t install or import the SDK
[ ] Performance - Performance issues
[x] Behaviour - Functions aren’t working as expected (Such as generate URL)
[ ] Documentation - Inconsistency between the docs and behaviour
[ ] Other (Specify)

## Operating System
[ ] Linux
[ ] Windows
[x] OSX
[ ] All

## Environment and Libraries (fill in the version numbers)
Cloudinary Ruby SDK version - 1.16.0
Ruby Version - 2.4.0
Rails Version - 4.2

**Comment by aleksandar-cloudinary** [comment]
Hi @deberle. Thanks for reporting. We will look into this from our side and share an update afterwards.

**Comment by const-cloudinary** [comment]
Hi @deberle , the issue should be fixed in version 1.16.1

**Comment by aleksandar-cloudinary** [comment]
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
