### ISSUE TITLE
1.18.0 Broken

### ISSUE THREAD

**Issue by ollym** [cloudinary/cloudinary_gem#426]
From the changelog:

 * Update embedded `jquery.cloudinary.js` to fix ES5 compatibility issue

I can't see the commit where this has been updated?

**Comment by const-cloudinary** [comment]
@ollym It is part of the rake build:

https://github.com/cloudinary/cloudinary_gem/blob/f96f3ce23d0b1ecbf3c8b58d6ee6081f5228bd90/Rakefile#L13

cloudinary_js was broken in the previous builds, wanted to indicate that it is fixed in the change log.

**Comment by const-cloudinary** [comment]
@ollym , thanks for the report!
A new version is released, please check it out:
[1.18.1](https://github.com/cloudinary/cloudinary_gem/releases/tag/1.18.1)
