### ISSUE TITLE
Cant direct upload raw files

### ISSUE THREAD

**Issue by Mrodrides** [cloudinary/cloudinary_gem#473]
When implementing a direct upload in a rails form specifiying direct_upload: true, the api returns a 400 response due to the lack of format in the url search params.

This issue only happens in development and not all the times

## Issue Type (Can be multiple)
- [ ] Build - Cannot install or import the SDK
- [ ] Performance - Performance issues
- [x] Behaviour - Functions are not working as expected (such as generate URL)
- [ ] Documentation - Inconsistency between the docs and behaviour
- [ ] Other (Specify)

## Steps to reproduce
In a rails form add
`<%= f.file_field :data_file, direct_upload: true, accept: 'text/csv' %>`
Alert error appears

## Error screenshots or Stack Trace (if applicable)
![error message](https://user-images.githubusercontent.com/12738699/147245089-2f05bb21-fb5a-4f89-9ca0-9dfd5836e96c.png)

formed url on a successful attempt
`https://api.cloudinary.com/v1_1/cloud_name/raw/upload?api_key=key&context=active_storage_key%3DUeaRoJ5eyEs6a3E6cr1UFjEn&format=csv&public_id=id&signature=signature&timestamp=1640264587`

Format url on a failed attempt
`https://api.cloudinary.com/v1_1/cloud_name/image/upload?api_key=444276538933115&context=active_storage_key%3DhBSN6VN1PdqAq4TPtbPS4L69&public_id=id&signature=signature&timestamp=1640265086`

As you can see in the server logs image im not getting the right url

<img width="1680" alt="Captura de pantalla 2021-12-23 a las 14 29 30" src="https://user-images.githubusercontent.com/12738699/147247394-502dba2c-8458-48be-a8fa-deeeb6b6957f.png">

As you can see is uploading the csv as an image

## Operating System
- [ ] Linux
- [ ] Windows
- [x] macOS
- [ ] All

## Environment and Libraries (fill in the version numbers)
- Cloudinary Ruby SDK version - 1.21.0
- Ruby Version - 2.7.5
- Rails Version - 5.2.2 
- Other Libraries (Carrierwave, ActiveStorage, etc) - ActiveStorage

## Repository

If possible, please provide a link to a reproducible repository that showcases the problem

**Comment by igy** [comment]
Hi Miguel,

Thanks for contacting us. 

I hate to ask a potentially silly question, but are you certainly using v1.21.0 of the SDK in both your production and development environments? 

I ask because v1.19.0 of the Ruby SDK included a bugfix to resolve an issue that's very similar to what you've described here, and earlier versions can be expected to have this error in the scenario you've described. 

The code that was added and an accompanying note can be seen here: https://github.com/cloudinary/cloudinary_gem/blob/b6f084b3a0f7697aa0d4c96f2201e069ee12d66d/lib/active_storage/service/cloudinary_service.rb#L75-L85

If you do have v1.21.0 (or some other version above 1.19.0), were you able to identify any common factor for the requests that fail? Is the upload filename, including the extension, certainly available to your frontend code, for it to be passed to our SDK and from there to our API?

Thanks,
Stephen

**Comment by Mrodrides** [comment]
Hello @igy thanks for your answer,

I tried to even lock the version in the gemfile `gem 'cloudinary', '~> 1.21.0'` but it didn't work It does not detect.
Ive unpacked the gem and debugged using byebug, i found the following results:
![image](https://user-images.githubusercontent.com/12738699/147928518-c347242c-6055-4553-ada9-4d4e5a35ffb3.png)
Here content_type is '' as io is nil and the key is just a string, this method is called here

![image](https://user-images.githubusercontent.com/12738699/147928598-0ba2d471-b2f0-4b92-9c5f-01e7b24b52f3.png)

thus when calling `content_type_to_resource_type` with content_type as empty string it returns an image

**Comment by Mrodrides** [comment]
Ive done a couple of modifications to sort this issue:

![image](https://user-images.githubusercontent.com/12738699/147938960-2f6233d9-ce6c-428d-9ae6-04a9181ac7a1.png)
Ive modified the resource_type method to accept a third argument
![image](https://user-images.githubusercontent.com/12738699/147939040-86a8385f-a394-42a1-bc1b-2cb1cdfd699c.png)
Also moved the guard clause in the ext_for_file method
![image](https://user-images.githubusercontent.com/12738699/147939110-b6e49de3-aa0e-4d86-bb49-6bafc0bfc2c4.png)
It works for me but I dont know if I break any other uses of this gem

**Comment by d-mendoza** [comment]
If you open rails console in that project, what version do you get?

**Comment by Mrodrides** [comment]
It's 5.2.2

**Comment by d-mendoza** [comment]
My apologies, I meant to say, can you do this:

```
rails c
require 'cloudinary'
Cloudinary::VERSION
```

I just want to make sure the version is right.

**Comment by Mrodrides** [comment]
![image](https://user-images.githubusercontent.com/12738699/148743927-d1410f5e-0ec8-4a3e-acaa-70d756a74cd6.png)

**Comment by Mrodrides** [comment]
Ive been reviewing the code of active storage to check differences between 5.2 and 7.0

5.2 activestorage/app/controllers
![image](https://user-images.githubusercontent.com/12738699/148744264-34ccb6e3-e0dd-49e0-87ca-5680279704cf.png)

Same folder in 7.0
![image](https://user-images.githubusercontent.com/12738699/148744312-9174c43b-f77e-4302-bd81-156f43d4014e.png)

Differences are massive, it is probably the cause of the issue.

**Comment by momoip** [comment]
I'm checking internally and will keep you posted.

**Comment by momoip** [comment]
I've opened an internal ticket for this issue and will keep you posted.

**Comment by Mrodrides** [comment]
Thank you @momoip

**Comment by momoip** [comment]
@Mrodrides Of course.  Will for sure let you know when the issue is fixed and deployed.

**Comment by tommyg-cld** [comment]
@Mrodrides apologies for the delay, so we tested with csv files and cannot replicate on Rails 7.0.4
We got valid upload URLs and everything works as expected. We always saw the file content type detected right.

Are you still having this issue? If so, is it with specific CSV files and can you send us this file? Does upgrading to rails 7.0.4 help as well?

**Comment by Mrodrides** [comment]
Previously we had to vendorize the gem and modify it there but now we have upgraded raise and teared down all the internal hacks, so is back to normal.
Everything works correctly with the images and pdfs, but the raw files are still problematic, and worst of all the bugs are not consitent.

When for example i upload a csv, docx or a txt file, sometimes the url has the extension and sometimes it does not.
So when for example it is displayed in the app through the 'attachment.url(secure: true)' it leads to a 404, removing or adding .csv, .txt or .docx on the file solves the issue.

I have to remark here that we only use direct uploads.

On the other side, i notice that when in the console i do

<img width="1200" alt="image" src="https://user-images.githubusercontent.com/12738699/206160567-2b75d298-a5eb-4bd7-bad7-a1355960c8d5.png">

As you can see, one has the format and the other not

**Comment by tommyg-cld** [comment]
@Mrodrides thanks for getting back. How often are you seeing extensions not being included for raw files? Do you see any pattern in them? And is it happening on random raw files?

**Comment by austenmadden** [comment]
We were experiencing this same problem. We were on `v1.23.0` and the fix included in `v.1.24.0` found [here](https://github.com/cloudinary/cloudinary_gem/commit/d250d5265dab9991f28c5a398894dd8c3c9a46d3) resolved it.
