### ISSUE TITLE
Support Dynamic Folder upload parameters

### ISSUE THREAD

**Issue by key88sf** [cloudinary/cloudinary_gem#478]
## Feature request for Cloudinary Ruby SDK
Please add support for passing `asset_folder`, `display_name`, `public_id_prefix`, `use_filename_as_display_name` when uploading via `Cloudinary::Uploader.upload` method.

## Explain your use case
You have already added support for these to other SDKs, as listed here:
https://cloudinary.com/documentation/dynamic_folders#new_parameters

The Ruby SDK should be updated as well!

## Describe the problem you’re trying to solve
Trying to programmatically upload in Ruby/Rails using features of Dynamic Folders.

## Do you have a proposed solution?
Yes - https://github.com/cloudinary/cloudinary_gem/pull/479

**Comment by key88sf** [comment]
@const-cloudinary Thank you! Will you be bumping the official gem version anytime soon?

**Comment by const-cloudinary** [comment]
@key88sf , yes, it will be released today.
