### ISSUE TITLE
Update API is missing metadata support

### ISSUE THREAD

**Issue by Qapybara28** [cloudinary/cloudinary_gem#495]
## Bug report for Cloudinary Ruby SDK
Before proceeding, please update to latest version and test if the issue persists

## Describe the bug in a sentence or two.

Not possible to update metadata using the Update API because it wasn't implemented

This line is missing from https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/api.rb#L256:
```ruby
:metadata            => Cloudinary::Utils.encode_context(options[:metadata]),
```
(maybe rename encode_context to something more generic)

Documentation: https://cloudinary.com/documentation/admin_api#update_details_of_an_existing_resource
…

## Issue Type (Can be multiple)
- [ ] Build - Cannot install or import the SDK
- [ ] Performance - Performance issues
- [X] Behaviour - Functions are not working as expected (such as generate URL)
- [ ] Documentation - Inconsistency between the docs and behaviour
- [ ] Other (Specify)

## Steps to reproduce

```ruby
Cloudinary::Api.update(public_id, metadata: {something: 'value'})
```
Doesn't update the metadata (missing from the request)

**Comment by thomasgurung-cloudinary** [comment]
Hi there,

Thanks for reaching out. Let me check on that more but for now, you can instead use the [explicit API](https://cloudinary.com/documentation/image_upload_api_reference#explicit) which is not rate-limited either.

`Cloudinary::Uploader.explicit("hsn0oa42bj9zgv7wdfr4g3xiufhi", :type => "upload", :metadata => "smd_external_id=ruby_test")`

Per docs, this field accepts a pipe-separated list of custom metadata fields (by external_id) and the values to assign to each of them. The =, " and ❘ characters can be supported as values when escaped with a prepended backslash (\).
For example: in_stock_id=50❘color_id=[\"green\",\"red\"].

Thanks,
Thomas

**Comment by thomasgurung-cloudinary** [comment]
No problem, I'll keep you posted regarding the Cloudinary::Api.update() function.
