### ISSUE TITLE
Conditional metadata rules support

### ISSUE THREAD

**Issue by Qapybara28** [cloudinary/cloudinary_gem#497]
## Feature request for Cloudinary Ruby SDK

Currently the SDK is lacking support for the conditional metadata rules API (enterprise only) documented here:
https://cloudinary.com/documentation/conditional_metadata_rules_api

## Describe the problem you’re trying to solve
There is no interface on cloudinary website to CRUD conditional metadata rules, it's only accessible through the API so I need to use it.

## Do you have a proposed solution?
Extending Cloudinary::Api with new endpoints

**Comment by Qapybara28** [comment]
Will prepare a MR if I find some time

**Comment by rikuoCloudinary** [comment]
Hi @Qapybara28, 

I believe you are looking for the ability to create conditional metadata rules through the UI/DAM.

We have a guide on how to accomplish his here: 
https://cloudinary.com/documentation/dam_admin_structured_metadata#managing_conditional_metadata_rules

We typically see our users utilizing the UI/DAM to create these initially, then using the API to utilize them. 

Please let me know if I've misunderstood the request/issue.

**Comment by Qapybara28** [comment]
Hello @rikuoCloudinary,

The source of truth regarding the structured metadata fields and rules configurations is in my application to allow seemless migration (upsert) so using the UI/DAM isn't enough.

What I'm asking for is the implementation of the ruby wrapping for the conditional metadata rules CRUD which is currently missing.

Side note: It seems there is a configuration issue on my enterprise account because the conditional metadata rules editor isn't available.

**Comment by Qapybara28** [comment]
Issue regarding my account has been resolved (feature wasn't enabled by default)

**Comment by jackiecatania** [comment]
Thank you for letting us know @Qapybara28! So glad that your issue is resolved.

**Comment by Qapybara28** [comment]
Is there any update for the original request ?

**Comment by jackiecatania** [comment]
@Qapybara28 after reviewing your original request and checking on our side it looks like this hasn't been implemented for any of our SDKs but I have sent a request to our SDK team to see if this is something they can add as a feature request.
