### ISSUE TITLE
ActiveStorage: Non-image file is not deleted when its blob is destroyed

### ISSUE THREAD

**Issue by zokioki** [cloudinary/cloudinary_gem#506]
## Describe the bug in a sentence or two.

When an `ActiveStorage::Blob` for a non-image file (e.g. a CSV) is destroyed, the corresponding file is not removed from the Cloudinary service. This seems to be due to [public_id](https://github.com/cloudinary/cloudinary_gem/blob/a555c1b41e12b14e339d90ef7f9c0136ab7cf13f/lib/active_storage/service/cloudinary_service.rb#L167) not generating the correct value for `raw`-type files (i.e. missing the file extension) as well as the incorrect value being passed to `resource_type` when calling [destroy](https://github.com/cloudinary/cloudinary_gem/blob/a555c1b41e12b14e339d90ef7f9c0136ab7cf13f/lib/active_storage/service/cloudinary_service.rb#L103).

## Issue Type
- [x] Behaviour - Functions are not working as expected (such as generate URL)

## Steps to reproduce

Given a standard Rails app with a `Report` model:

```ruby
class Report < ApplicationModel
  has_one_attached :csv
end
```

- Create a report record with an attached CSV file.
- Destroy the newly created report record.
- The `ActiveStorage::PurgeJob` will be enqueued but the file will not be deleted from Cloudinary.

## Notes

Given a blob for a CSV file with a key of `p5gnxhfu5a8h5zque0tevapn1tmh`, the following is ultimately called when attempting to [delete](https://github.com/cloudinary/cloudinary_gem/blob/a555c1b41e12b14e339d90ef7f9c0136ab7cf13f/lib/active_storage/service/cloudinary_service.rb#L96-L105) its file from the Cloudinary service:

```ruby
Cloudinary::Uploader.destroy("p5gnxhfu5a8h5zque0tevapn1tmh", resource_type: "image")
```

The above fails to delete the file, returning `{"result"=>"not found"}`. Modifying the call to add the file extension to the key and to use the correct resource_type results in a successful deletion:

```ruby
Cloudinary::Uploader.destroy("p5gnxhfu5a8h5zque0tevapn1tmh.csv", resource_type: "raw")
```

## Operating System
- [ ] Linux
- [ ] Windows
- [ ] macOS
- [x] All

## Environment and Libraries
- Cloudinary Ruby SDK version - 1.23.0
- Ruby version - 3.1.2
- Rails version - 7.0.4 
- ActiveStorage version - 7.0.4

**Comment by aleksandar-cloudinary** [comment]
Hi @zokioki - Thanks for reporting this - I'll go through it and share more details afterwards.

**Comment by const-cloudinary** [comment]
Hello @zokioki.

There is a fix for adding file extension for raw files:
https://github.com/cloudinary/cloudinary_gem/pull/507
It will be merged soon.

It fixes the file extension problem.

Regarding `resource_type: "image"` for your CSV file. 

Can you please provide your file?

We tried to reproduce it on our end and the resource_type was detected correctly.

Thanks!

**Comment by zokioki** [comment]
@const-cloudinary Thanks for the quick work on the fix. 

It looks like my assumption about the `resource_type` mismatch was incorrect. When composing this issue, I assumed the key passed to the [resource_type](https://github.com/cloudinary/cloudinary_gem/blob/a555c1b41e12b14e339d90ef7f9c0136ab7cf13f/lib/active_storage/service/cloudinary_service.rb#L99) method was the blob's raw `key` string, but it appears that it is an instance of `ActiveStorage::BlobKey`, which contains the file's content_type and results in the appropriate resource type. 

It seems that the extension logic was the only issue here.

**Comment by const-cloudinary** [comment]
@zokioki , in addition to the PR mentioned above there is another PR (#508) that takes the content type parameter directly from the function, without passing it through the `ActiveStorage::BlobKey`, hopefully it should resolve the issue.
If not, please provide the `csv` file you are uploading and we can investigate it further. Mime type detection is not always accurate.
Thanks once again for raising the issue!
