### ISSUE TITLE
Get resource count

### ISSUE THREAD

**Issue by manuelmeurer** [cloudinary/cloudinary_gem#52]
There doesn't seem to be a way to get a resource count from the API at the moment, right?
Something like "count the number of resources with tag 'foo'".
Are there plans to add something like that at some point in time?

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Comment by manuelmeurer** [comment]
Well, it would have been nice to get an answer to my question in the last two years... :(

**Comment by taragano** [comment]
I apologize for that. I have mistakenly thought that you got an answer via our support system, but apparently this was another user, sorry about that. 
While it is not yet implemented, it's on our road map to support image count via the Admin API. I'll be happy to let you know of any updates.

**Comment by manuelmeurer** [comment]
Ok thanks! No, I don't think I ever got an answer from the support system.

**Comment by const-cloudinary** [comment]
Cloudinary [Search API](https://cloudinary.com/documentation/search_api#response) can be used to get count of the resources.
