### ISSUE TITLE
Update sample projects dependencies

### ISSUE THREAD

**Issue by const-cloudinary** [cloudinary/cloudinary_gem#523]
## Feature request for Cloudinary Ruby SDK
Sample projects located here:
https://github.com/cloudinary/cloudinary_gem/tree/master/samples

are a bit outdated, they use old ruby/rails versions.

Since they are not a part of the library delivered to users, they can be safely updated to the latest versions of ruby, rails and other dependencies.

## Do you have a proposed solution?

Update samples to use the latest versions of language/frameworks.

**Comment by HeetVekariya** [comment]
@const-cloudinary I would like work on this issue, can you please give me the details that what examples i have to add.

**Comment by const-cloudinary** [comment]
@HeetVekariya thank you for your interest in this.
It's not about adding new samples, but updating existing projects, for example this one:
https://github.com/cloudinary/cloudinary_gem/blob/master/samples/user_profiles_active_storage/Gemfile

You can see that the versions there are a bit old. 

It would be nice to update this sample to the latest version of ruby(3.2), rails(7), perform migrations, make sure everything works as expected, maybe add a few examples of the things that were introduced in the latest rails.

**Comment by Vishalk91-4** [comment]
@const-cloudinary, can you please assign this issue to me
You mean I have to use rvm to change ruby version and gem rails, latest to update rails version
Then I have to change outdated methods in each project also

Do I have to do something like this or something else

**Comment by colbyfayock** [comment]
@HeetVekariya are you working on this?
