### ISSUE TITLE
Folders in public_id not respected in remote url

### ISSUE THREAD

**Issue by ehoch** [cloudinary/cloudinary_gem#66]
Create an uploader/model with a folder.  Try and use remote_image_url with it.  It does not respect the folder names from the public_id.

Works great in the renamer with direct javascript upload....

**Comment by harsh15** [comment]
This is still not fixed.
I have raised the issue, please can u quickly respond.
here is the issue
https://github.com/cloudinary/cloudinary_gem/issues/162

**Comment by taragano** [comment]
Hi, 
Unfortunately we couldn't reproduce this issue. 
Can you please share your uploader? Specifically how you overrode the public_id method?
