### ISSUE TITLE
Migrator doesn't work for Mongoid

### ISSUE THREAD

**Issue by bobbywilson0** [cloudinary/cloudinary_gem#67]
This is pretty clear based on the sqlite3 requirement, but I think it should probably be noted somewhere. Ideally, there would be a workaround for mongoid.

**Comment by tocker** [comment]
sqlite3 is not required for this gem.
As for mongoid, see [CarrierWave Mongoid support](https://github.com/carrierwaveuploader/carrierwave-mongoid).

I'm closing this issue due to the elapse time, but feel free to contact our [support](http://support.cloudinary.com) or create a new issue here.
