### ISSUE TITLE
Conditional processing

### ISSUE THREAD

**Issue by bobbywilson0** [cloudinary/cloudinary_gem#68]
In CarrierWave you can do something like this:

```ruby
process :my_process, :if => :my_condition?

def my_process
  #do stuff
end

def my_condition?
  model.condition?
end
```

However this doesn't work in the cloudinary version

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
