### ISSUE TITLE
Uploader retrieves any supplied string as File

### ISSUE THREAD

**Issue by jredburn** [cloudinary/cloudinary_gem#75]
We ran into a security issue where we were passing in a user-supplied string to `Cloudinary::Uploader#upload` without sanitization. This allowed a malicious user to put in a URL for a remote image such as `/etc/passwd` and grab the file from the local filesystem. We are now sanitizing the input, but wanted to flag the issue as a potential security hole for others.

**Comment by tocker** [comment]
Thank you for pointing this issue out.
The is beyond the scope of the gem, as it is platform specific, and should be resolve on a system level.
