### ISSUE TITLE
rake cloudinary:sync_static with multiple cloudinary account

### ISSUE THREAD

**Issue by Maxim-Filimonov** [cloudinary/cloudinary_gem#79]
Hey Cloudinary Team,
Following the guidelines from the [support request](http://support.cloudinary.com/entries/23190918-Can-I-use-multiple-clouds-on-a-single-account-) for multiple environments in cloudinary I've created two accounts in cloudinary for staging and production. 
For staging I execute CLOUDINARY_URL=staging_url rake cloudinary:sync_static which creates .cloudinary.static and I commit it to develop branch.
When I merge develop branch to master and run CLOUDINARY_URL=production_url rake cloudinary:sync_static no images get's uploaded to production cloudinary account. The only workaround I've found is to remove .cloudinary.static file from master without committing and then do rake sync_static which will create file with exactly the exactly the same content.
I had a look at the code for the task and looks like [the problem](https://github.com/cloudinary/cloudinary_gem/blob/ea522884110eaab1a0f62f7179b9501956058d06/lib/cloudinary/static.rb#L87) is that the only thing that sync_static checks is public signature of the file and if matches then it doesn't upload the file which in case of different account is not gonna work.
The easy fix would be to allow to override location of metadata file so that I can do something like CLOUDINARY_URL=production_url rake cloudinary:sync_static metadata:./.cloudinary.production.static
Even better would be able to be able to provide a method for cloudinary to get a file from whatever location i want, e.g.
```
#Custom metadata file location
class Cloudinary::Static
  def self.metadata_file
    # Simple match by rails env
    filename = ".cloudinary.#{RAILS_ENV}.static"
    @file = File.open(filename) if File.exists?(filename)
    # Something more complex like getting file from S3 for instance, 
    # which will allow to use rake cloudinary:sync_static  on a build server without worrying of committing it back
  end
  def self.save_metadata
    # For a simple match
    @file.close
    # Upload to S3 or any custom logic to save metadata file
  end
end
```
What are you thoughts on this? I want to do a pull request but want to run it with you first.

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
