### ISSUE TITLE
Cloudinary::Utils.cloudinary_url is destructive to the options hash passed into it

### ISSUE THREAD

**Issue by wam** [cloudinary/cloudinary_gem#91]
Looks like this is noted in `lib/cloudinary/utils.rb` in a couple of url generation methods. I'd like to avoid this. Is there a big downside to cloning the options hash inside these methods?

Thanks!

**Comment by jfcalvo** [comment]
Same problem here. 

This looks like a bad coding practice, modify received parameters is not a good idea. Thank god that I was freezing the hash used as parameter so I have received the following error:

```
RuntimeError: can't modify frozen Hash
```

I'm using the following parameters:

```ruby
CLOUDINARY_VIDEO_PARAMETERS = {
  width: 720,
  height: 720,
  video_codec: "h264",
  bit_rate: 800,
  gravity: :north,
  crop: :fill,
  resource_type: :video,
  secure: true
}

Cloudinary::Utils.cloudinary_url("my_global_id_resource.mp4", CLOUDINARY_VIDEO_PARAMETERS)
```

After execute that `CLOUDINARY_VIDEO_PARAMETERS` has the following content:

```ruby
{
     :width => 720,
    :height => 720
}
```

This is a big mistake, you need to fix that.

(BTW: If you want to temporarily avoid this problem you can use `dup` passing options to the method)

**Comment by joekur** [comment]
:+1: This is causing bad stuff for a multi-image uploader with the attachinary gem. Since that will loop over calling `Cloudinary::Utils.cloudinary_url` for each image, only the first thumbnail will fetch the thumbnail size that we want, and every other image will be fetched in full size (as the `crop` key gets deleted).

**Comment by tocker** [comment]
You are all correct. Unfortunately because changing `Cloudinary::Utils.cloudinary_url` may break some of the users' code we'll have to wait for the next major release of the library to make this change.

**Comment by asisayag2** [comment]
This will be handled in the next major version
