### ISSUE TITLE
undefined method `cloudinary_url' for Cloudinary::Utils:Class

### ISSUE THREAD

**Issue by nickcoyne** [cloudinary/cloudinary_gem#92]
Periodically we receive error messages like this in our app running on Heroku (Unicorn).  An application restart solves the problem. At the moment I have no idea if it is an Heroku issue, or could there be something from Cloudinary causing trouble. The message doesn't really make sense to me since the method is clearly available in the class.

Any suggestions welcome.

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
