### ISSUE TITLE
Static Images

### ISSUE THREAD

**Issue by kris** [cloudinary/cloudinary_gem#96]
Hi,

I've followed the following tutorial:

http://cloudinary.com/blog/how_to_deliver_your_static_images_through_a_cdn_in_ruby_on_rails

The issue I'm having is that I enabled it for development, and the image_tag helper isn't pointing to Cloudinary, but to localhost, but the images aren't loading locally now. I'm wondering if there is a step I missed that is causing this to happen? This is on a legacy 3.2 app using Carrierwave and cloudinary-1.0.66

Thanks

**Comment by taragano** [comment]
Closing this issue due to the time elapsed.
Please feel free to contact our support http://support.cloudinary.com or create a new ticket if you have any additional issues.
