### ISSUE TITLE
Carrierwave + Mongoid 4 : updating an image let the old identifier in place

### ISSUE THREAD

**Issue by nicolasblanco** [cloudinary/cloudinary_gem#99]
Hi,

I've got a Rails 4 application, using Mongoid 4 and carrierwave.

The behaviour is that when I update a record with a mounted uploader with no image, the record is saved with the currently good identifier. But if I try to update the image, the old identifier stays in place.

I investigated the problem and noticed that the runtime goes normally to this line: 
https://github.com/cloudinary/cloudinary_gem/blob/master/lib/cloudinary/carrier_wave/storage.rb#L82
where Mongoid set method is called with the new identifier.
But when I look at Moped logs, I can see that the $set method is done with the old identifier!

I looked at Mongoid#set method here: 
https://github.com/mongoid/mongoid/blob/master/lib/mongoid/persistable/settable.rb#L25

Mongoid first sends all the attributes on the setter method and retrieves the attribute value using the attributes hash. The problem here is that when the new identifier is sent to the setter, this does not change the attributes hash which still contains the old identifier. Result : the $set command is always called with the old identifier.

What do you think of this weird problem?

Thanks.

**Comment by taragano** [comment]
Hi @nicolasblanco,
I see your last response from quite a time ago. I just wanted to check whether you still experience the same (or any other) issue?

**Comment by taragano** [comment]
@nicolasblanco - Do you still experience this issue?
As it's been a while since the last response, I'll close this issue now, but please feel free to re-open it if you need any further assistance.

Thanks,
Itay
